### PR TITLE
fix: init ascend device if `AscendHAMiVNPUEnable` is disabled

### LINKED ISSUE #4773: [Bug] load ascend vnpu config Ascend310P
### Description

Currently, during the scheduler scheduling process, even if I don't need to use ascend NPU scheduling, there are still a large number of logs like this:
```
I1201 01:55:32.883127 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:32.883264 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:32.883514 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:32.883573 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.358798 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.358898 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.358977 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.359049 40728 device_info.go:97] Failed to get node devices. nodeName n2, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.359315 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.359387 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.359476 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.359542 40728 device_info.go:97] Failed to get node devices. nodeName n2, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.838695 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.838870 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.838952 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.839049 40728 device_info.go:97] Failed to get node devices. nodeName n2, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.839343 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.839430 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:33.839512 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:33.839593 40728 device_info.go:97] Failed to get node devices. nodeName n2, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:34.304156 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:34.306463 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
I1201 01:55:34.306685 40728 device_info.go:547] load ascend vnpu config Ascend310P: {Ascend310P 310P3 huawei.com/Ascend310P huawei.com/Ascend310P-memory 21527 24576 8 7 [{vir01 3072 1 1} {vir02 6144 2 2} {vir04 12288 4 4}]}
W1201 01:55:34.306756 40728 device_info.go:97] Failed to get node devices. nodeName n1, deviceType Ascend310P, error annos not found hami.io/node-register-Ascend310P
```

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

It's not what we want, only we want hami ascend device scheduling feature and want to use 310p device, then scheduler should report such logs. Currently should not influence the normal scheduling process

### What version of Volcano are you using?

master

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by DSFans2014**
Fixes #4773

### CODE REVIEW

File: pkg/scheduler/api/node_info.go [hunk 1]
```diff
@@ -352,9 +352,11 @@ func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
 	ni.Others[vgpu.DeviceName] = vgpu.NewGPUDevices(ni.Name, node)
```
Comment (JesseStutler) [inline pkg/scheduler/api/node_info.go]: Could you also provide other switches for these gpu and vnpu devices? Looks like it will init by default when we don't enable device share plugin

File: pkg/scheduler/api/node_info.go [hunk 2]
```diff
@@ -347,21 +347,26 @@ func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
...
-		ascend_ignored_list = append(ascend_ignored_list, devices.GetIgnoredDevices()...)
-	}
-	IgnoredDevicesList.Set(
-		ni.Others[gpushare.DeviceName].(Devices).GetIgnoredDevices(),
-		ni.Others[vgpu.DeviceName].(Devices).GetIgnoredDevices(),
-		ni.Others[vnpu.DeviceName].(Devices).GetIgnoredDevices(),
-		ascend_ignored_list,
-	)
+	ignored_list := []string{}
+	if gpushare.GpuSharingEnable || gpushare.GpuNumberEnable {
```
Comment (JesseStutler) [inline pkg/scheduler/api/node_info.go:351]: Why is this an OR switch instead of a global switch such as `gpushare.GPUEnable`?

Comment (DSFans2014) [reply pkg/scheduler/api/node_info.go:351]: I referenced the code here.
https://github.com/volcano-sh/volcano/blob/499546a8157922e079a8b3106437f4cba42c5387/pkg/scheduler/api/node_info.go#L512-L514

File: pkg/scheduler/api/node_info.go [hunk 3]
```diff
@@ -347,21 +347,26 @@ func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
...
+		ni.Others[gpushare.DeviceName] = gpushare.NewGPUDevices(ni.Name, node)
+		ignored_list = append(ignored_list, gpushare.NewGPUDevices(ni.Name, node).GetIgnoredDevices()...)
+	}
+	if vgpu.VGPUEnable {
```
Comment (archlitchi) [inline pkg/scheduler/api/node_info.go:355]: Have you tried vGPU end Ascend vnpu functions after this modification?

Because vgpu.VGPUEnable is set in deviceshare plugin, and nodeInfo is probably initialized before that plugin set the VGPUEnable to true, this change may break the function of vGPU and vNPU
