### PR TITLE
fix issue 2957: predicate plugin ut didn't really run due to kubeclient init failed

### LINKED ISSUE #2957: UT didn't really run because of kubeclient init failed
**What happened**:
https://github.com/volcano-sh/volcano/blob/9427174e0eefc18d321d34ba844fe3f80ff491a5/pkg/scheduler/plugins/predicates/predicates_test.go#L68-L71

image

**What you expected to happen**:

UT should use k8s's fakeclient

**How to reproduce it (as minimally and precisely as possible)**:

add log before return
```go
	klog.Errorf("exiting test...")
```

**Anything else we need to know?**:

all cases in predicate and nodeorder plugin which need k8s client

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lowang-bh**
Fix #2957(UT didn't really run because of kubeclient init failed)

image

### CODE REVIEW

File: pkg/scheduler/plugins/drf/hdrf_test.go [hunk 1]
```diff
@@ -252,7 +252,7 @@ func TestHDRF(t *testing.T) {
 
 		binder := &util.FakeBinder{
 			Binds:   map[string]string{},
-			Channel: make(chan string),
```
Comment (Monokaix) [inline pkg/scheduler/plugins/drf/hdrf_test.go:255]: Why change to 300?

File: pkg/scheduler/plugins/predicates/predicates_test.go [hunk 2]
```diff
@@ -84,97 +57,41 @@ func TestEventHandler(t *testing.T) {
...
 	// tests
-	tests := []struct {
-		name     string
-		pods     []*apiv1.Pod
-		nodes    []*apiv1.Node
-		pcs      []*schedulingv1.PriorityClass
-		pgs      []*schedulingv1beta1.PodGroup
-		expected map[string]string
-	}{
+	tests := []uthelper.TestCommonStruct{
```
Comment (Monokaix) [inline pkg/scheduler/plugins/predicates/predicates_test.go:74]: every test case will initialize a new scheduler cache, but the origin test has a global schdeuler cache, is there any effect?

File: pkg/scheduler/actions/allocate/allocate_test.go [hunk 3]
```diff
@@ -323,7 +323,7 @@ func TestAllocateWithDynamicPVC(t *testing.T) {
 			fakeVolumeBinder := util.NewFakeVolumeBinder(kubeClient)
 			binder := &util.FakeBinder{
 				Binds:   map[string]string{},
-				Channel: make(chan string),
```
Comment (Monokaix) [inline pkg/scheduler/actions/allocate/allocate_test.go:326]: Why change to 10？

File: pkg/scheduler/plugins/drf/hdrf_test.go (hunk 1 above)
Comment (lowang-bh) [reply pkg/scheduler/plugins/drf/hdrf_test.go:255]: To avoid blocking binding in FakeBinder. Please review PR#3343 first.

File: pkg/scheduler/actions/allocate/allocate_test.go (hunk 3 above)
Comment (lowang-bh) [reply pkg/scheduler/actions/allocate/allocate_test.go:326]: same as above.

File: pkg/scheduler/plugins/predicates/predicates_test.go (hunk 2 above)
Comment (lowang-bh) [reply pkg/scheduler/plugins/predicates/predicates_test.go:74]: No effect. There is just one case now.

**Review by william-wang — APPROVED** [review]
/approve
