### PR TITLE
Replace queue status update by using ApplyStatus method

### LINKED ISSUE #4139: can not submit topology vcjob, volcano version is 1.11.0-network-topology-preview
### Description

we alredy install volcano,but can not submit job
# kubectl -n ai-vtraining get all
NAME                                       READY   STATUS      RESTARTS   AGE
pod/volcano-admission-67c95f5864-b7mph     1/1     Running     0          13s
pod/volcano-admission-init-ctc6t           0/1     Completed   0          13s
pod/volcano-controllers-6b8b64cb79-9zflg   1/1     Running     0          13s
pod/volcano-scheduler-7f985cc86b-4hgch     1/1     Running     0          13s

NAME                                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/volcano-admission-service     ClusterIP   10.43.90.179   <none>        443/TCP    14s
service/volcano-controllers-service   ClusterIP   10.43.193.70   <none>        8081/TCP   14s
service/volcano-scheduler-service     ClusterIP   10.43.27.194   <none>        8080/TCP   14s

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/volcano-admission     1/1     1            1           14s
deployment.apps/volcano-controllers   1/1     1            1           14s
deployment.apps/volcano-scheduler     1/1     1            1           14s

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/volcano-admission-67c95f5864     1         1         1       14s
replicaset.apps/volcano-controllers-6b8b64cb79   1         1         1       14s
replicaset.apps/volcano-scheduler-7f985cc86b     1         1         1       14s

NAME                               COMPLETIONS   DURATION   AGE
job.batch/volcano-admission-init   1/1           10s        14s

queue:
# kubectl get queue default -oyaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  creationTimestamp: "2025-03-24T06:44:49Z"
  generation: 2
  managedFields:
  - apiVersion: scheduling.volcano.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:guarantee: {}
        f:reclaimable: {}
        f:weight: {}
      f:status:
        .: {}
        f:reservation: {}
    manager: vc-scheduler
    operation: Update
    time: "2025-03-24T06:44:49Z"
  - apiVersion: scheduling.volcano.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:parent: {}
    manager: vc-controller-manager
    operation: Update
    time: "2025-03-24T06:44:54Z"
  name: default
  resourceVersion: "9602311120"
  uid: 7afb5ad8-6171-417f-ba20-9cd4f151a9d5
spec:
  guarantee: {}
  parent: root
  reclaimable: true
  weight: 1

# kubectl get queue root -oyaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  creationTimestamp: "2025-03-24T06:44:49Z"
  generation: 1
  managedFields:
  - apiVersion: scheduling.volcano.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:guarantee: {}
        f:reclaimable: {}
        f:weight: {}
      f:status:
        .: {}
        f:reservation: {}
    manager: vc-scheduler
    operation: Update
    time: "2025-03-24T06:44:49Z"
  name: root
  resourceVersion: "9602310412"
  uid: 61e700c9-3b7a-4be8-8a9b-bf66e6b63f52
spec:
  guarantee: {}
  reclaimable: false
  weight: 1

bug:
# kubectl apply -f vcjob-topo.yaml
Error from server: error when creating "vcjob-topo.yaml": admission webhook "validatejob.volcano.sh" denied the request: can only submit job to queue with state `Open`, queue `default` status is ``;

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

the topology job can running,and the job can schdule the node which according the topology param

### What version of Volcano are you using?

1.11.0-network-topology-preview

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by JesseStutler**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Currently, the vc-controller must specify the allocated field to update the status because allocated is not optional. The scheduler also updates allocated, which may potentially lead to conflicts, causing the queue to not open:
https://github.com/volcano-sh/volcano/blob/1ae9a84e16bb327aa54420863cba3c4588e6e325/pkg/controllers/queue/queue_controller_action.go#L101-L107

Therefore, the fields updated by the scheduler and controller cannot conflict. The scheduler is only responsible for updating the allocated field in status, and the controller is only responsible for updating the state field in status. Currently, the controller has used ApplyStatus to update the state. For consistency, the scheduler also uses AppyStatus and declares the fields it manages.

#### Which issue(s) this PR fixes:

Fixes #4139 

#### Validation
Queue can successfully open and update allocated in status:
eaa8209ac3950a97cd0f52392743c1f
5262a5dae07bd51dd01cc9c27aa834c
bd450ffe124c27099be5ad03bd6a824

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by JesseStutler** [comment]
After https://github.com/volcano-sh/apis/pull/163 merged, I will update the apis dependency version in go.mod

**Comment by JesseStutler** [comment]
PTAL @Monokaix @hwdef @lowang-bh

**Review by hwdef — COMMENTED** [review]
lgtm

File: pkg/scheduler/util/scheduler_helper.go [hunk 1]
```diff
@@ -34,7 +34,11 @@ import (
 	"volcano.sh/volcano/pkg/scheduler/api"
 )
 
-const baselinePercentageOfNodesToFind = 50
+const (
+	baselinePercentageOfNodesToFind = 50
+
+	DefaultFieldManager = "vc-scheduler"
```
Comment (Monokaix) [inline pkg/scheduler/util/scheduler_helper.go:40]: component is better.

Comment (JesseStutler) [reply pkg/scheduler/util/scheduler_helper.go]: Done. Thanks
