### PR TITLE
resource compare support only consider the requested resource item

### LINKED ISSUE #3520: overcommit plugin is no need to check other resources.
**What happened**:

I created a vcjob to request 0.1 core CPU, but the podgroup is pending. I add some debug info logs to source code, and recompile the volcano-scheduler to replace the old one. I found the reason of pending is that the minReq's "nvidia.com/gpu" resouce is less than idle.
However, my vcjob didn't request the "nvidia.com/gpu" resouce. Finally I realized that the `jobMinReq` will add the inqueue's request resources and comparing with idle resources. Actually, the total amount of "nvidia.com/gpu" requested by inqueue is already more than idle.

https://github.com/volcano-sh/volcano/blob/c61742d2aee80e0fdc920f1d71ee7457a7e9e582/pkg/scheduler/plugins/overcommit/overcommit.go#L122

**What you expected to happen**:

I think that when adding newly requested resources to inqueued resources, irrelevant resources should not be considered.  For example, if the minimum request is only 1 CPU core, then there is no need to add memory, GPU and other resources.

**How to reproduce it (as minimally and precisely as possible)**:

I guess it may be possible to reproduce it by doing the following:
1. Add and register GPU resources to one node of clusters.
2. Create a vcjob to request GPU resources.
3. When podgorup is running, remove the node from clusters.
4. The podgroup's status may become "Inqueue".
5. Then create a new vcjob to request only cpu or memory resource.
6. The new podgroup will be pending because of Inqueue's GPU not enough.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
v1.9.0
- Kubernetes version (use `kubectl version`):
v1.25.4
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lowang-bh**
fixes #3520

some times, we need to only compare the required dimensions in the resource.
eg: when check  `Enqueueable`, `Allocatable` or `Preemptive`, even overused.
Will use this function to replcae comparision in `AddJobEnqueueableFn`, `AddPreemptiveFn` and `AddAllocatableFn`

- [x] AddJobEnqueueableFn
- [ ] AddAllocatableFn
- [ ] AddPreemptiveFn
- [ ] AddOverusedFn

### CODE REVIEW

File: pkg/scheduler/api/resource_info.go [hunk 1]
```diff
@@ -429,6 +429,36 @@ func (r *Resource) LessEqual(rr *Resource, defaultValue DimensionDefaultValue) b
...
+	}
+
+	// if r.scalar is nil, whatever rr.scalar is, r is less or equal to rr
+	if r.ScalarResources == nil {
+		return true
+	}
+
+	for name, quant := range req.ScalarResources {
+		rQuant := r.ScalarResources[name]
+		rrQuant := rr.ScalarResources[name]
```
Comment (Monokaix) [inline pkg/scheduler/api/resource_info.go:454]: Shuould check rr not nil.

Comment (lowang-bh) [reply pkg/scheduler/api/resource_info.go:460]: Done.

File: pkg/scheduler/api/resource_info.go [hunk 2]
```diff
@@ -429,6 +429,42 @@ func (r *Resource) LessEqual(rr *Resource, defaultValue DimensionDefaultValue) b
...
```
Comment (hwdef) [inline pkg/scheduler/api/resource_info.go:460]: Will rQuant or rrQuant be nil?

Comment (lowang-bh) [reply pkg/scheduler/api/resource_info.go:460]: They are float values.

Comment (hwdef) [reply pkg/scheduler/api/resource_info.go:460]: I mean not getting it

**Review by hwdef — COMMENTED** [review]
/lgtm

File: pkg/scheduler/api/resource_info_test.go [hunk 3]
```diff
@@ -753,6 +753,81 @@ func TestLessEqual(t *testing.T) {
...
+				MilliCPU: 4, Memory: 4000,
+				ScalarResources: map[v1.ResourceName]float64{"nvidia.com/gpu": 1},
+			},
+			resource2: &Resource{MilliCPU: 8, Memory: 8000},
+			req: &Resource{
+				MilliCPU: 4, Memory: 2000,
+				ScalarResources: map[v1.ResourceName]float64{"nvidia.com/gpu": 1},
+			},
+			expected: false,
+		},
```
Comment (Monokaix) [inline pkg/scheduler/api/resource_info_test.go:805]: Why this return false?

File: pkg/scheduler/api/resource_info_test.go [hunk 4]
```diff
@@ -753,6 +753,81 @@ func TestLessEqual(t *testing.T) {
...
+			},
+			resource2: &Resource{
+				MilliCPU: 100, Memory: 8000,
+				ScalarResources: map[v1.ResourceName]float64{"nvidia.com/A100": 1},
+			},
+			req: &Resource{
+				MilliCPU: 10, Memory: 4000,
+				ScalarResources: map[v1.ResourceName]float64{"nvidia.com/gpu": 0, "nvidia.com/A100": 1, "scalar": 1},
+			},
+			expected: true,
```
Comment (Monokaix) [inline pkg/scheduler/api/resource_info_test.go:819]: Why true? resource2 has no dimension `"scalar": 1`.

File: pkg/scheduler/api/resource_info.go [hunk 5]
```diff
@@ -429,6 +429,42 @@ func (r *Resource) LessEqual(rr *Resource, defaultValue DimensionDefaultValue) b
 	return true
 }
 
+// LessEqualWithDimension only compare the resource items in req param
```
Comment (Monokaix) [inline pkg/scheduler/api/resource_info.go:432]: I think we should clarify that this func behaves when one dimension of request missed in resource1 and when no dimension missed in resource1 but less than resource1.

Comment (Monokaix) [reply pkg/scheduler/api/resource_info.go:432]: seems that we only consider whether the dimension exists but not care the specific value of it, right?

File: pkg/scheduler/api/resource_info.go [hunk 6]
```diff
@@ -429,6 +429,42 @@ func (r *Resource) LessEqual(rr *Resource, defaultValue DimensionDefaultValue) b
...
+// @param req define the resource item to be compared
+// if req is nil, equals r.LessEqual(rr, zero)
+func (r *Resource) LessEqualWithDimension(rr *Resource, req *Resource) bool {
```
Comment (Monokaix) [inline pkg/scheduler/api/resource_info.go:435]: How about just remove the dimensions not in `req` of `r`, then compare just like before?

File: pkg/scheduler/api/resource_info_test.go (hunk 3 above)
Comment (lowang-bh) [reply pkg/scheduler/api/resource_info_test.go:805]: req need gpu resource with 1， and resource2 has no gpu, so it can not satisfy the request.

File: pkg/scheduler/api/resource_info.go (hunk 6 above)
Comment (lowang-bh) [reply pkg/scheduler/api/resource_info.go:435]: also ok.

Comment (Monokaix) [reply pkg/scheduler/api/resource_info.go:435]: I think this way is more readable.

File: pkg/scheduler/api/resource_info_test.go (hunk 4 above)
Comment (lowang-bh) [reply pkg/scheduler/api/resource_info_test.go:819]: It means resource1's `scalar` less equal to resource2's `scalar`.

File: pkg/scheduler/api/resource_info.go (hunk 5 above)
Comment (lowang-bh) [reply pkg/scheduler/api/resource_info.go:432]: > seems that we only consider whether the dimension exists but not care the specific value of it, right?

yes

**Comment by Monokaix** [comment]
`Overused` should also be considered.

File: pkg/scheduler/api/resource_info_test.go [hunk 7]
```diff
@@ -753,6 +753,81 @@ func TestLessEqual(t *testing.T) {
...
+		},
+	}
+
+	for i, test := range tests {
```
Comment (Monokaix) [inline pkg/scheduler/api/resource_info_test.go:823]: Please also add a case:
r1'cpu resource > r2'cpu resource, while req has no cpu resource but has a enough scalar resource, it's expected to return true.

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by hwdef** [comment]
because lgtm has been added by @Monokaix
