### PR TITLE
don't enable error cache if task role spec is empty

### LINKED ISSUE #3527: `PredicateNodes` function default enable ErrorCache, and offen disturb UT case
The `errorCache` feature can be used when job's tasks have a same spec key to improve proformance.
However, if the spec key is empty for some tasks in a job and predicate failed, then those tasks with empty spec key in this job will all be failed in predicate action.
`taskGroupID`
```go
func taskGroupID(task *api.TaskInfo) string {
	return fmt.Sprintf("%s/%s", task.Job, task.GetTaskSpecKey())
}
```

#### What would you like to be added:
Two solotions:
- 1. add a config param to control the switch of err cache
- 2. if task spec key is empty, don't use error cache

#### Why is this needed:

1. save debug time when write testcases, It has disturb me several times that pods can not work as expect
2. in some user scene using volcano scheduler without controller, this may cause job cannot be scheduled if user forget to set spec

### LINKED ISSUE #3666: When the Gang policy(JobReadyFn) is enabled，cache in the  Predicate phase of the scheduling cycle causes a scheduling failure
### Description

The tasks submitted will have the following requirements
**1. Pods in a Job are not the same, perhaps with different resource requirements, perhaps with different node affinities, etc
2. the **Gang** policy(JobReadyFn) is enabled**

**In this case, all pods in a Job will use the same Predicate cache. When a Pod fails to **Predicate**  a node, that node will never be considered.This may cause the task to fail.**

I think you can't assume that the Pods under the Job are all the same, so you shouldn't use the same cache, and can the Predicate cache switch be configured?

attention: I used a third-party platform to submit the Job, not Volcano Job

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

I think you can't assume that the Pods under the Job are all the same, so you shouldn't use the same cache, and can the Predicate cache switch be configured?

### What version of Volcano are you using?

release v1.9.0

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by lowang-bh**
fixes #3527
fixes #3666

### CODE REVIEW

File: pkg/scheduler/actions/allocate/allocate.go [hunk 1]
```diff
@@ -199,7 +199,10 @@ func (alloc *Action) allocateResourcesForTasks(tasks *util.PriorityQueue, job *a
 			break
 		}
 
-		predicateNodes, fitErrors := ph.PredicateNodes(task, allNodes, alloc.predicate, true)
+		// don't enable error cache if task's TaskRole is empty, because different pods with empty TaskRole will all
+		// have the same taskGroupID, and one pod predicate failed, all other pods will also be failed
+		// see issue: https://github.com/volcano-sh/volcano/issues/3527
+		predicateNodes, fitErrors := ph.PredicateNodes(task, allNodes, alloc.predicate, len(task.TaskRole) != 0)
```
Comment (Monokaix) [inline pkg/scheduler/actions/allocate/allocate.go:205]: So where to add the switch?

Comment (Monokaix) [inline pkg/scheduler/actions/allocate/allocate.go:205]: In what case the task.TaskRole is empty?

**Comment by Monokaix** [comment]
What's difference between this and `cacheEnable` in predict plugin?

File: pkg/scheduler/actions/allocate/allocate.go (hunk 1 above)
Comment (lowang-bh) [reply pkg/scheduler/actions/allocate/allocate.go:205]: Current implementation don't need switch anymore. It will be disabled when task role is empty,other wise enable it.

Comment (lowang-bh) [reply pkg/scheduler/actions/allocate/allocate.go:205]: Eg, testcase forget to set it.  Workloads doesn't set it in pod when just scheduler is used.

File: pkg/scheduler/actions/backfill/backfill.go [hunk 2]
```diff
@@ -76,7 +76,7 @@ func (backfill *Action) Execute(ssn *framework.Session) {
 			break
 		}
 
-		predicateNodes, fitErrors := ph.PredicateNodes(task, ssn.NodeList, predicateFunc, true)
+		predicateNodes, fitErrors := ph.PredicateNodes(task, ssn.NodeList, predicateFunc, len(task.TaskRole) != 0)
```
[the remark this answers is not in the document]
Comment (lowang-bh) [reply pkg/scheduler/actions/backfill/backfill.go:79]: It is also ok.

File: pkg/scheduler/actions/allocate/allocate.go (hunk 1 above)
Comment (Monokaix) [reply pkg/scheduler/actions/allocate/allocate.go:205]: All none vcjob will meet this problem？

File: pkg/scheduler/actions/backfill/backfill.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Monokaix) [reply pkg/scheduler/actions/backfill/backfill.go:79]: I think we can add a switch, becasue we can compare the different performance with this feature enable/disabled.

[the remark this answers is not in the document]
Comment (lowang-bh) [reply pkg/scheduler/actions/backfill/backfill.go:79]: Add a switch for cache, but still keep disabled for empty taskrole, right?

[the remark this answers is not in the document]
Comment (Monokaix) [reply pkg/scheduler/actions/backfill/backfill.go:79]: Yeah.

File: pkg/scheduler/actions/allocate/allocate.go [hunk 3]
```diff
@@ -199,7 +210,10 @@ func (alloc *Action) allocateResourcesForTasks(tasks *util.PriorityQueue, job *a
 			break
 		}
 
-		predicateNodes, fitErrors := ph.PredicateNodes(task, allNodes, alloc.predicate, true)
+		// don't enable error cache if task's TaskRole is empty, because different pods with empty TaskRole will all
```
Comment (Monokaix) [inline pkg/scheduler/actions/allocate/allocate.go:213]: Put these comments into pkg/scheduler/util/predicate_helper.go is better.

File: pkg/scheduler/api/well_known_labels.go [hunk 4]
```diff
@@ -42,4 +42,7 @@ const (
 
 	// topologyDecisionAnnotation is the key of topology decision about pod request resource
 	topologyDecisionAnnotation = "volcano.sh/topology-decision"
+
```
Comment (Monokaix) [inline pkg/scheduler/api/well_known_labels.go:45]: Can we put it into another file? Because it's not a label.

File: pkg/scheduler/api/constants.go [hunk 5]
```diff
@@ -0,0 +1,6 @@
+package api
+
+const (
+	// EnablePredicateErrCacheKey is the key whether predicate error cache is enabled
+	EnablePredicateErrCacheKey = "enable.predicateErrorCache"
```
Comment (Monokaix) [inline pkg/scheduler/api/constants.go:5]: Can we refer to plugin's option definition？Because it's also an option or param of action.

Comment (lowang-bh) [reply pkg/scheduler/api/constants.go:5]: such as `allocate.predicateErrorCacheEnable` or `predicateErrorCacheEnable`?

Comment (Monokaix) [reply pkg/scheduler/api/constants.go:5]: Yeah.

Comment (lowang-bh) [reply pkg/scheduler/api/constants.go]: Has changed to `predicateErrorCacheEnable`.

File: pkg/scheduler/api/constants.go [hunk 6]
```diff
@@ -0,0 +1,6 @@
+package api
+
+const (
+	// EnablePredicateErrCacheKey is the key whether predicate error cache is enabled
+	EnablePredicateErrCacheKey = "predicateErrorCacheEnable"
```
Comment (Monokaix) [inline pkg/scheduler/api/constants.go:5]: A little doubt, seems it's just a param and not an API, can we put it in another place?

Comment (hwdef) [reply pkg/scheduler/api/constants.go:5]: +1

Comment (lowang-bh) [reply pkg/scheduler/api/constants.go:5]: how about put them in `pkg/scheduler/conf/scheduler_conf.go`?

Comment (hwdef) [reply pkg/scheduler/api/constants.go]: I think this will be fine
