### PR TITLE
Fix:  Sync Jobflow status with vcjob Status Terminated

### LINKED ISSUE #4442: When Vcjob Terminated, Jobflow always pending
### Description

bad case:
```yaml
Name:         gpu-task-avocado-1e0bd46462
Namespace:    xxxx
Labels:       <none>
Annotations:  <none>
API Version:  flow.volcano.sh/v1alpha1
Kind:         JobFlow
Spec:
  Flows:
    Name:  template-avocado
  Job Retain Policy:   retain
Status:
  Conditions:
    gpu-task-avocado-1e0bd46462-template-avocado:
      Create Time:       2025-07-08T08:21:04Z
      Phase:             Terminated
      Running Duration:  2m45s
  Job Status List:
    End Timestamp:  2025-07-08T08:23:49Z
    Name:           gpu-task-avocado-1e0bd46462-template-avocado
    Running Histories:
      End Timestamp:    2025-07-08T08:23:49Z
      Start Timestamp:  2025-07-08T08:21:04Z
      State:            Pending
      End Timestamp:    2025-07-08T08:23:49Z
      Start Timestamp:  2025-07-08T08:23:49Z
      State:            Terminating
      Start Timestamp:  2025-07-08T08:23:49Z
      State:            Terminated
    Start Timestamp:    2025-07-08T08:21:04Z
    State:              Terminated
  State:
    Phase:  Pending
  Terminated Jobs:
    gpu-task-avocado-1e0bd46462-template-avocado
Events:  <none>
```

### Steps to reproduce the issue

update jobflow status

### Describe the results you received and expected

update jobflow status: 

### What version of Volcano are you using?

v1.11

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by dongjiang1989**
#### Which issue(s) this PR fixes:

Fixes #4442

#### Does this PR introduce a user-facing change?

```release-note
Sync Jobflow status with vcjob Status Terminated
```

### CODE REVIEW

**Comment by dongjiang1989** [comment]
cc @Monokaix  PTAL

File: pkg/controllers/jobflow/state/pending.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ func (p *pendingState) Execute(action jobflowv1alpha1.Action) error {
 		return SyncJobFlow(p.jobFlow, func(status *jobflowv1alpha1.JobFlowStatus, allJobList int) {
 			if (len(status.RunningJobs) > 0 || len(status.CompletedJobs) > 0) && len(status.FailedJobs) <= 0 {
 				status.State.Phase = jobflowv1alpha1.Running
-			} else if len(status.FailedJobs) > 0 { // TODO(dongjiang1989) Modify it when the if condition judgment is implemented
+			} else if len(status.FailedJobs) > 0 || len(status.TerminatedJobs) > 0 { // TODO(dongjiang1989) Modify it when the if condition judgment is implemented
```
Comment (Monokaix) [inline pkg/controllers/jobflow/state/pending.go:33]: Is there a middle state for terminated job like terminated instead of failed? I'm not sure whether it's suitable to set a failed state.

Comment (dongjiang1989) [reply pkg/controllers/jobflow/state/pending.go:33]: It is forcibly terminated due to an error, or the number of retries is exhausted, resulting in the state remaining in `Terminated`.  It is a final state.
