### PR TITLE
Fix panic while `vcctl queue list` after podgroups' queue was deleted

### LINKED ISSUE #4427: Vcctl panic while listing queues after queue was deleted but podgroups remain
### Description

When a queue is removed, but there is still some podgroups belonging to this queue. Using `vcctl queue list` command for querying queues will cause a panic.

### Steps to reproduce the issue

1. Create a queue
```
$ kubectl get q 
NAME      AGE
default   98d
root         56d
test          5s
```
2. Create some podgroups belonging to this queue
```
$ kubectl get pg -owide
NAME                                                                                         STATUS    MINMEMBER   RUNNINGS   AGE   QUEUE
test1-ea5776cd-6337-4a0e-b0cf-11570828baf7      Running   1                          1                       10s     test
test2-3cd12bbe-59b1-4345-a1f4-716d451bd3ad   Running   1                                                    3s       test
```
3. Delete the queue
```
$ kubectl delete q test
queue.scheduling.volcano.sh "test" deleted
```
4. use `vcctl queue list` to query queues
```
$ vcctl queue list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x15d4909]

goroutine 1 [running]:
volcano.sh/volcano/pkg/cli/podgroup.(*PodGroupStatistics).StatPodGroupCountsForQueue(...)
        /volcano/pkg/cli/podgroup/podgroup.go:20
volcano.sh/volcano/pkg/cli/queue.ListQueue({0x1bf90c0, 0x291c560})
        /volcano/pkg/cli/queue/list.go:107 +0x489
main.buildQueueCmd.func4(0xc00027ef08, {0x1960e18?, 0x4?, 0x1960e1c?})
        /volcano/cmd/cli/queue.go:66 +0x29
github.com/spf13/cobra.(*Command).execute(0xc00027ef08, {0x291c560, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xc00032e308)
       /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
       /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/component-base/cli.run(0xc00032e308)
        /go/pkg/mod/k8s.io/component-base@v0.32.2/cli/run.go:143 +0x245
k8s.io/component-base/cli.Run(0xc00032e308?)
        /go/pkg/mod/k8s.io/component-base@v0.32.2/cli/run.go:44 +0x17
main.main()
        /volcano/cmd/cli/vcctl.go:43 +0x1c5

```

### Describe the results you received and expected

After the queue was deleted, `vcctl queue list` command will ignore the podgroups whose queues are deleted, and won't panic.

### What version of Volcano are you using?

master

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by halcyon-r**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When using `vcctl queue list` for querying queues, if a podgroup's queue does not exist, ignore it. To prevent panic and display the result correctly.

#### Which issue(s) this PR fixes:

Fixes #4427 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Monokaix** [comment]
Thanks! Please fix ci.

File: pkg/cli/queue/list.go [hunk 1]
```diff
@@ -104,6 +104,10 @@ func ListQueue(ctx context.Context) error {
 	}
 
 	for _, pg := range pgList.Items {
+		_, ok := queueStats[pg.Spec.Queue]
```
Comment (Monokaix) [inline pkg/cli/queue/list.go:107]: Mayebe we can also add ut?

Comment (halcyon-r) [reply pkg/cli/queue/list.go:107]: Sure

File: pkg/cli/queue/queue_test.go [hunk 2]
```diff
@@ -249,3 +250,83 @@ test-queue               1       Open    root    1       2       3       4
...
+
+	testcase := struct {
+		Name        string
+		ExpectError error
+	}{
+		Name:        "List queues with residual podgroups",
+		ExpectError: nil,
+	}
+	err := ListQueue(context.TODO())
+	if err != nil && err.Error() != testcase.ExpectError.Error() {
```
Comment (JesseStutler) [inline pkg/cli/queue/queue_test.go]: I think a more accurate judgment should be based on the results printed to stdout, rather than whether ListQueues has an error, because the data returned by your mock server is correct and never meet an error

File: pkg/cli/queue/queue_test.go [hunk 3]
```diff
@@ -249,3 +250,83 @@ test-queue               1       Open    root    1       2       3       4
...
+			val, err := json.Marshal(podGroups)
+			if err == nil {
+				w.Write(val)
+			}
+		}
+	})
+	return httptest.NewServer(handler)
+}
+
+// https://github.com/volcano-sh/volcano/issues/4427
```
Comment (JesseStutler) [inline pkg/cli/queue/queue_test.go]: Should explain more detail of it, rather than paste a link here

Comment (halcyon-r) [reply pkg/cli/queue/queue_test.go]: OK

File: pkg/cli/queue/queue_test.go (hunk 2 above)
Comment (halcyon-r) [reply pkg/cli/queue/queue_test.go]: This looks a bit hard to test, let me try.

Comment (halcyon-r) [reply pkg/cli/queue/queue_test.go]: @JesseStutler Please take another look

**Review by JesseStutler — COMMENTED** [review]
/lgtm
Great work!
