### PR TITLE
[release-1.12] Cherry-pick #4786 and #4792

### LINKED ISSUE #4827: [release-1.12] fix: replicaset KubeGroupNameAnnotation handling
Manual cherrypick required.

#4792 failed to apply on top of branch "release-1.12":
```
Applying: fix: podgroup controller replicaset annotation fix
Using index info to reconstruct a base tree...
M	pkg/controllers/podgroup/pg_controller_handler.go
Falling back to patching base and 3-way merge...
Auto-merging pkg/controllers/podgroup/pg_controller_handler.go
CONFLICT (content): Merge conflict in pkg/controllers/podgroup/pg_controller_handler.go
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 fix: podgroup controller replicaset annotation fix
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by hajnalmt**
#### What type of PR is this?
Cherry-picking to the release-1.12 branch:
Relevant part of:
https://github.com/volcano-sh/volcano/pull/4792
and:
https://github.com/volcano-sh/volcano/pull/4786 

#### Which issue(s) this PR fixes:

Fixes #4827 

#### Does this PR introduce a user-facing change?

```release-note
fix(pg_controller): replicaset update did not synchronize the new podgroup informations
fix(pg_controller): replicasets were creating an unnecessary podgroup even though KubeGroupNameAnnotation was present
```

### CODE REVIEW

File: pkg/controllers/podgroup/pg_controller_handler.go [hunk 1]
```diff
@@ -104,9 +104,16 @@ func (pg *pgcontroller) addReplicaSet(obj interface{}) {
...
+				klog.V(4).Infof("Pod %s is already associated with a podgroup %s", klog.KObj(&pod), pgName)
+				return
+			}
+			// In the upgrade scenario, need to synchronize and update the podgroup-related information.
+			// For example, if you update `scheduling.volcano.sh/group-min-member: "2"`, the podgroup's `minMember` needs to be updated to 2.
+			err := pg.createOrUpdateNormalPodPG(&pod)
 			if err != nil {
-				klog.Errorf("Failed to create PodGroup for pod %s: %v", klog.KObj(&pod), err)
+				klog.Errorf("Failed to create or update PodGroup for pod %s: %v", klog.KObj(&pod), err)
 			}
```
[the remark this answers is not in the document]
Comment (hajnalmt) [reply pkg/controllers/podgroup/pg_controller_handler.go:117]: You mixed up the things here this is not needed.

File: pkg/controllers/podgroup/pg_controller.go [hunk 2]
```diff
@@ -132,7 +132,7 @@ func (pg *pgcontroller) Run(stopCh <-chan struct{}) {
 		}
 	}
 
-	for i := 0; i < int(pg.workers); i++ {
+	for range int(pg.workers) {
```
[the remark this answers is not in the document]
Comment (hajnalmt) [reply pkg/controllers/podgroup/pg_controller.go:135]: We use go 1.23 on this branch too let's move on.

Comment (hzxuzhonghu) [inline pkg/controllers/podgroup/pg_controller.go:135]: why do we backport the cleanup?

File: pkg/controllers/podgroup/pg_controller_handler.go [hunk 3]
```diff
@@ -104,9 +104,16 @@ func (pg *pgcontroller) addReplicaSet(obj interface{}) {
...
-			err := pg.createNormalPodPGIfNotExist(&pod)
+			// If the pod is already associated with a podgroup, skip creating a new one.
+			if pgName := pod.Annotations[scheduling.KubeGroupNameAnnotationKey]; pgName != "" {
+				klog.V(4).Infof("Pod %s is already associated with a podgroup %s", klog.KObj(&pod), pgName)
+				return
+			}
+			// In the upgrade scenario, need to synchronize and update the podgroup-related information.
+			// For example, if you update `scheduling.volcano.sh/group-min-member: "2"`, the podgroup's `minMember` needs to be updated to 2.
+			err := pg.createOrUpdateNormalPodPG(&pod)
 			if err != nil {
```
Comment (hzxuzhonghu) [inline pkg/controllers/podgroup/pg_controller_handler.go:115]: I am concerned we donot even have a test for this bug fix

File: pkg/controllers/podgroup/pg_controller.go (hunk 2 above)
Comment (hajnalmt) [reply pkg/controllers/podgroup/pg_controller.go:135]: I cherrypicked the whole commit, we are using go 1.23 on release-1.12 so it looked logical for me.
Shall I remove it?

File: pkg/controllers/podgroup/pg_controller_handler.go (hunk 3 above)
Comment (hajnalmt) [reply pkg/controllers/podgroup/pg_controller_handler.go:115]: This bothers me too. 👍 shall I write one? Maybe we don't need in these cherrypicks but it would be good to be present at least on master.
https://github.com/volcano-sh/volcano/pull/4786 didn't have one and I just cherrypicked it.

Comment (hzxuzhonghu) [reply pkg/controllers/podgroup/pg_controller_handler.go:115]: Yes, i think we need one.

File: pkg/controllers/podgroup/pg_controller.go (hunk 2 above)
Comment (hzxuzhonghu) [reply pkg/controllers/podgroup/pg_controller.go:135]: Got it, not a big problem

**Comment by JesseStutler** [comment]
Due to disk space, @hajnalmt mate please rebase the latest release-1.12 codes, I think I'm ok with this but yes we should add tests for it

**Comment by JesseStutler** [comment]
@hajnalmt I'm going to release v1.12.3, could you help rebase it?

**Comment by hajnalmt** [comment]
Rebased sry!
I have tried to create a unit test for:
https://github.com/volcano-sh/volcano/pull/4786
But the test actually failed, and I don't understand why yet so I need to do some investigation to understand what I messed up there, but it's on my backlog 👍

**Comment by JesseStutler** [comment]
I think I'm ok with it, @hajnalmt will help add uts, we could backport this pr first
/lgtm
/cc @hzxuzhonghu
