### PR TITLE
fix: ci err caused bt ray e2e default image

### LINKED ISSUE #4669: Ray E2E Test default image is not available
### Description

Ray E2E Test default image is not available [repo link](https://hub.docker.com/r/bitnami/ray)
As a result, All of E2E Sequence is failed. (It looks kind of serious to me)

We need to change a image from bitnami/ray:2.49.0 to [rayproject/ray:2.49.0](https://hub.docker.com/r/rayproject/ray) Apache2.0 image.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Recently, the tests were failed.
Image

I checked journal.log in the e2e test log. I found that bitnami/ray:2.49.0 could not be pulled.

Image

### What version of Volcano are you using?

1.13.0

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by Wonki4**
#### What type of PR is this?
Fix ci error caused by ray default image.

#### What this PR does / why we need it:
When ray e2e sequence test is executed, the pod could not pull the e2e default image(bitnami/ray:2.49.0, not found)

```
Oct 02 06:57:23 integration-worker2 kubelet[273]: E1002 06:57:23.173290     273 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"ray\" with ImagePullBackOff: \"Back-off pulling image \\\"bitnami/ray:2.49.0\\\": ErrImagePull: rpc error: code = NotFound desc = failed to pull and unpack image \\\"docker.io/bitnami/ray:2.49.0\\\": failed to resolve reference \\\"docker.io/bitnami/ray:2.49.0\\\": docker.io/bitnami/ray:2.49.0: not found\"" pod="erli6hgc/ray-cluster-job-head-0" podUID="433a6958-3d9e-43cc-9d14-965b43db6541"
```

Because bitnami no longer provide the image. [bitnami/ray:2.49.0](https://hub.docker.com/r/bitnami/ray)
image

#### Which issue(s) this PR fixes:

Fixes #4669 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: test/e2e/util/util.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ const (
 	DefaultTFImage      = "volcanosh/dist-mnist-tf-example:0.0.1"
 	// "volcanosh/pytorch-mnist-v1beta1-9ee8fda-example:0.0.1" is from "docker.io/kubeflowkatib/pytorch-mnist:v1beta1-9ee8fda"
 	DefaultPytorchImage = "volcanosh/pytorch-mnist-v1beta1-9ee8fda-example:0.0.1"
-	DefaultRayImage     = "bitnami/ray:2.49.0"
+	DefaultRayImage     = "rayproject/ray:2.49.0"
```
[the remark this answers is not in the document]
Comment (Wonki4) [reply test/e2e/util/util.go:86]: https://hub.docker.com/layers/rayproject/ray/2.49.0

2.49.0 is valid and stable version.

**Comment by Wonki4** [comment]
@Monokaix 

Could you share your result of #4642 about [deleting docker images](https://github.com/volcano-sh/volcano/compare/37300b8b457012915211e4d1e049cb644be12838..e480023548dfeee431ae73504033b069c8e80d08) in test/e2e/jobseq package?

File: test/e2e/jobseq/common.go
Comment (JesseStutler) [inline test/e2e/jobseq/common.go:1]: I'm wondering if we do need this `PruneUnusedImagesOnAllNodes`? Cause https://github.com/volcano-sh/volcano/pull/4642 has already used `docker system prune` to free disk. The e2e testing is running on a github runner machine, and the runner machine runs a kind cluster, do we still need to list all the k8s nodes and exec `PruneUnusedImagesOnAllNodes`?

File: test/e2e/util/util.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (JesseStutler) [reply test/e2e/util/util.go:86]: > https://hub.docker.com/layers/rayproject/ray/2.49.0
> 
> 2.49.0 is valid and stable version.

After you changed the ray image, can the flaky test be fixed? Do we still need to prune the images?

**Comment by Monokaix** [comment]
There is some misunderstanding, https://github.com/volcano-sh/volcano/pull/4642 just load volcano components images to control-plane node because volcano is only deployed in that node.

File: test/e2e/jobseq/common.go
Comment (Wonki4) [reply test/e2e/jobseq/common.go:1]: I saw the PR and I knew that the code for prune was deleted.
The final change is related to loading vc images in control plane node.

Comment (JesseStutler) [reply test/e2e/jobseq/common.go:1]: Oh sorry, I thought that [deleting docker images](https://github.com/volcano-sh/volcano/compare/37300b8b457012915211e4d1e049cb644be12838..e480023548dfeee431ae73504033b069c8e80d08) was merged in #4642

**Comment by JesseStutler** [comment]
@Wonki4 I think we should also cherry-pick it to release-1.13 once we merge it

**Comment by JesseStutler** [comment]
/cc @hwdef @Monokaix @lowang-bh 
Could you approve this?

**Comment by Wonki4** [comment]
> @Wonki4 I think we should also cherry-pick it to release-1.13 once we merge it 

Okay, I think you're right

**Comment by hajnalmt** [comment]
Thank you for merging this guys!
We will need to cherry-pick this to release-1.13 too. Will you do it @Wonki4 ?
