### PR TITLE
fix: Fix jobflow `status` confusion problem

### LINKED ISSUE #4089: When multiple jobflows are executed concurrently (these multiple jobflows reference the same jobTemplate template), each jobflow status has multiple jobflows and multiple vcjob information
### Description

When multiple jobflows are executed concurrently (these multiple jobflows reference the same jobTemplate template), each jobflow status has multiple jobflows and multiple vcjob information
```bash
 kubectl describe jf test-b
Name:         test-b
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  flow.volcano.sh/v1alpha1
Kind:         JobFlow
Metadata:
  Creation Timestamp:  2025-03-13T09:59:06Z
  Generation:          1
  Resource Version:    8057
  UID:                 0c67033b-f831-487c-8ca2-fb4ee1ff1892
Spec:
  Flows:
    Name:  a
    Depends On:
      Targets:
        a
    Name:  b
    Depends On:
      Targets:
        b
    Name:  c
    Depends On:
      Targets:
        b
    Name:  d
    Depends On:
      Targets:
        c
        d
    Name:             e
  Job Retain Policy:  retain
Status:
  Completed Jobs:     ---> muti jobflow info in this
    test-a-a
    test-a-c
    test-b-c
    test-b-d
    test-a-e
    test-b-e
    test-b-a
    test-a-b
    test-b-b
    test-a-d
  Conditions:
    Test - A - A:
.....
```

### Steps to reproduce the issue

1. create jobTemplate list：
```yaml
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: a
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx:1.14-alpine
              command:
                - sh
                - -c
                - sleep 60s
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 64m
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: b
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx:1.14-alpine
              command:
                - sh
                - -c
                - sleep 40s
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 100m
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: c
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx:1.14-alpine
              command:
                - sh
                - -c
                - sleep 30s
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 64m
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: d
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx:1.14-alpine
              command:
                - sh
                - -c
                - sleep 10s
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 64m
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: e
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx:1.14-alpine
              command:
                - sh
                - -c
                - sleep 10s
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 100m
          restartPolicy: OnFailure
```
2. create one jobflow, name: `test-a`
```yaml
apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: test-a
  namespace: default
spec:
  jobRetainPolicy: retain  # retain or delete
  flows:
    - name: a
    - name: b
      dependsOn:
        targets: ['a']
    - name: c
      dependsOn:
        targets: ['b']
    - name: d
      dependsOn:
        targets: ['b']
    - name: e
      dependsOn:
        targets: ['c','d']
```
3. At the same time， create one jobflow, name: `test-b`
```yaml
apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: test-b
  namespace: default
spec:
  jobRetainPolicy: retain  # retain or delete
  flows:
    - name: a
    - name: b
      dependsOn:
        targets: ['a']
    - name: c
      dependsOn:
        targets: ['b']
    - name: d
      dependsOn:
        targets: ['b']
    - name: e
      dependsOn:
        targets: ['c','d']
```

### Describe the results you received and expected

Expected:
I hope that the status in Jobflow A only contains the vcjob list information created by jobflowA; the status in Jobflow B only contains the vcjob list information created by jobflowB

Current phenomenon:
The vcjob lists created by Jobflow B and Jobflow A are all/partially mixed in the status of Jobflow B and Jobflow A.

### What version of Volcano are you using?

v1.11.0

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by dongjiang1989**
#### What type of PR is this?

Bugfix

#### What this PR does / why we need it:

1. Fix the confusion of `status` in jobflow specific scenarios
2. Add jobflow unittest case
3. Fixed and reopen skip unittest case

#### Which issue(s) this PR fixes:

Fixes #4089 

need cherry pick this PR to v1.10 and v1.11

#### Special notes for your reviewer:
@Monokaix 

#### Does this PR introduce a user-facing change?

```release-note
Fix the confusion of `status` in jobflow specific scenarios
```

### CODE REVIEW

File: pkg/controllers/jobflow/jobflow_controller_action_test.go [hunk 1]
```diff
@@ -256,10 +264,185 @@ func TestGetRunningHistoriesFunc(t *testing.T) {
...
+				t.Errorf("getAllJobsCreatedByJobFlow() gotJobsName = %v, wantJobsName %v", gotJobsName, tt.wantJobsName)
+			}
+		})
+	}
+}
+
 func TestGetAllJobStatusFunc(t *testing.T) {
-	// TODO(wangyang0616): First make sure that ut can run, and then fix the failed ut later.
-	// See issue for details: https://github.com/volcano-sh/volcano/issues/2851
-	t.Skip("Test cases are not as expected, fixed later. see issue: #2851")
```
Comment (dongjiang1989) [inline pkg/controllers/jobflow/jobflow_controller_action_test.go:262]: @wangyang0616  Fixed and reopen this case

**Comment by dongjiang1989** [comment]
cc @Monokaix PTAL

**Comment by Monokaix** [comment]
cc @hwdef

**Review by hwdef — COMMENTED** [review]
/lgtm

Thanks!

**Comment by dongjiang1989** [comment]
@hwdef  @Monokaix 
Need I cherry pick this PR to v1.10 and v1.11?

**Comment by Monokaix** [comment]
> @hwdef @Monokaix Need I cherry pick this PR to v1.10 and v1.11?

Yeah should backport.

**Comment by dongjiang1989** [comment]
> > @hwdef @Monokaix Need I cherry pick this PR to v1.10 and v1.11?
> 
> Yeah should backport.

I'm happy to finish it.
