### PR TITLE
bugfix: the csinode driver status failed updating

### LINKED ISSUE #2508: scheduler should not schedule when csinode driver restarts
**What happened**:
the csi plugin driver restarts but the csinode status not updated as what expected and the scheduler schedule a pod to the node even when the max volume count exceeds it's capacity

**What you expected to happen**:
update the csi node driver status correctly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: linux
- Volcano Version: 1.6.1
- Kubernetes version (use `kubectl version`):1.19
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by elinx**
fix #2508 the existing implementation still keeps the deleted driver
status as true, this pr fix it.

Signed-off-by: xilinxing <xilinxing@huawei.com>

### CODE REVIEW

File: pkg/scheduler/cache/event_handlers.go [hunk 1]
```diff
@@ -411,24 +411,18 @@ func (sc *SchedulerCache) AddOrUpdateCSINode(obj interface{}) {
...
-			DriverStatus: make(map[string]bool),
-		}
-		sc.CSINodesStatus[csiNode.Name] = csiNodeStatus
-	}
 
 	for i := range csiNode.Spec.Drivers {
 		d := csiNode.Spec.Drivers[i]
 		csiNodeStatus.DriverStatus[d.Name] = d.Allocatable != nil && d.Allocatable.Count != nil
 	}
+	sc.CSINodesStatus[csiNode.Name] = csiNodeStatus
```
Comment (william-wang) [inline pkg/scheduler/cache/event_handlers.go:425]: if csiNodeStatus exists in sc.CSINodesStatus[csiNode.Name], we still create a new csiNodeStatus?

Comment (elinx) [reply pkg/scheduler/cache/event_handlers.go:425]: Yes, the old status should be override completely because we don't know which driver pod is dead or recreated, otherwise there may left some non existent driver status as true.

Comment (jiangkaihua) [reply pkg/scheduler/cache/event_handlers.go:425]: Could we just remove the nonexistent drivers in existing `csiNodeStatus`, like:

```go
	for _, driver := range csiNode.Spec.Drivers {
		if _, exist := csiNodeStatus.DriverStatus[driver.Name]; !exist {
			delete(csiNodeStatus.DriverStatus, driver.Name)
			continue
		}
		csiNodeStatus.DriverStatus[driver.Name] = driver.Allocatable != nil && driver.Allocatable.Count != nil
	}
```

**Review by william-wang — APPROVED** [review]
/lgtm
