### PR TITLE
fix: events miss when there is a pod bind failed

### LINKED ISSUE #2865: if one pod binds failed, other pod's binding events lost
**What happened**:

successfully binding events miss when there is a pod bind failed

**What you expected to happen**:

each pod has a successfully binding event

**How to reproduce it (as minimally and precisely as possible)**:

code logical error as showed in code: if err !=nil, events of pods which are successfully bound will be drop.

https://github.com/volcano-sh/volcano/blob/ce14269e0166b04681a19caeaf92fc0ef775ceb9/pkg/scheduler/cache/cache.go#L791-L808

**Anything else we need to know?**:

handle binding results of both successful and failed tasks

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #2879: task scheduling latency metrics is not accurate
Have fix by #2866, just record issue.

**What happened**:

This Bind func never return error, so `UpdateTaskScheduleDuration` will always record all pods' successful binding time as now. But those pods failed to bind should not update metrics to now, due to they will be resynced and bounden in next cycle.

https://github.com/volcano-sh/volcano/blob/6b84f4b0f8a653d826ad7446d027ff12829efaa7/pkg/scheduler/cache/cache.go#L1052-L1060
**What you expected to happen**:

only handle metrics about successfully bind pods

**How to reproduce it (as minimally and precisely as possible)**:

code logic error

**Anything else we need to know?**:

Fix by #2866 : move metrics recording to where pod is bound 

**Environment**:
- Volcano Version: master branch
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lowang-bh**
Describe: fix #2865 that successfully binding events will lost if a pod is failed to bind; fix #2879 metrics not accurate

key points:
 1: replcace all clientset with interface
 2: move event and metrics recoding to where pod is successfully bounden
 3: add testcase about bind tasks

### CODE REVIEW

File: pkg/scheduler/cache/cache.go [hunk 1]
```diff
@@ -171,23 +171,21 @@ func (db *DefaultBinder) Bind(kubeClient *kubernetes.Clientset, tasks []*schedul
 			},
 			metav1.CreateOptions{}); err != nil {
 			klog.Errorf("Failed to bind pod <%v/%v> to node %s : %#v", p.Namespace, p.Name, task.NodeName, err)
-			errTasks = append(errTasks, task)
```
Comment (Monokaix) [inline pkg/scheduler/cache/cache.go:174]: maybe we can record successful bind event here and avoid lots of code change?

Comment (lowang-bh) [reply pkg/scheduler/cache/cache.go:174]: A good idea! But I find that it need a instance of event recorder. So is it need to put it in DefaultBinder or pass in as a param?

Comment (lowang-bh) [reply pkg/scheduler/cache/cache.go:174]: solved in latest commit.

**Comment by wangyang0616** [comment]
It's ok to me，please help to review. Thanks! @william-wang @jiangkaihua

**Comment by lowang-bh** [comment]
trigger ci

**Comment by lowang-bh** [comment]
@Thor-wl @hwdef Could you help review this pr? thanks.

**Review by hwdef — COMMENTED** [review]
/lgtm
I think this is OK, there is an unimportant suggestion that multiple commits can be split into multiple PRs.
Thanks for your contribution

File: pkg/scheduler/cache/factory.go [hunk 2]
```diff
@@ -1,17 +1 @@
 package cache
-
-// bindMethodMap Binder management
-var bindMethodMap Binder
-
-// RegisterBindMethod register Bind Method
-func RegisterBindMethod(binder Binder) {
```
Comment (william-wang) [inline pkg/scheduler/cache/factory.go:7]: This might break the existing users. Volcao allow user register custom binder.

**Comment by hwdef** [comment]
@lowang-bh Is this PR ready to be review?

**Comment by lowang-bh** [comment]
> @lowang-bh Is this PR ready to be review?

Yes, plz help to review, thanks. @hwdef  @wangyang0616 @Thor-wl

**Review by hwdef — COMMENTED** [review]
/lgtm
Not much different from my last review.
Thanks for your contribution.

**Comment by lowang-bh** [comment]
Hi, @william-wang , I updated this PR that newCache will create a new binder if there is no registered one.

image

**Comment by lowang-bh** [comment]
Hi, @wangyang0616, I think I have let it compariable with the old versions. The Bind Interface doesn't change. 
cc @william-wang

File: pkg/scheduler/cache/factory.go [hunk 3]
```diff
@@ -8,10 +8,7 @@ func RegisterBindMethod(binder Binder) {
 	bindMethodMap = binder
 }
 
+// GetBindMethod get the registered Binder
 func GetBindMethod() Binder {
 	return bindMethodMap
 }
-
```
Comment (william-wang) [inline pkg/scheduler/cache/factory.go:14]: The deletion impact `sc.Binder = GetBindMethod()`  in cache.go

Comment (william-wang) [reply pkg/scheduler/cache/factory.go:14]: I notice that you use another way to initilize the binder.  What is the advantage compared with the init() ? if no more benifit, we'd better keep it as it is :)

**Comment by william-wang** [comment]
@lowang-bh I merged your PR #3064, you need to refresh this PR.

File: pkg/scheduler/cache/factory.go (hunk 3 above)
Comment (lowang-bh) [reply pkg/scheduler/cache/factory.go:14]: NewDefaultBinder(old NewBinder) take two params: kubeClient, eventRecorder. It can not be done in init because those params has not be initialized.

**Comment by lowang-bh** [comment]
> @lowang-bh I merged your PR #3064, you need to refresh this PR.

This PR is based from https://github.com/volcano-sh/volcano/pull/3064. There will be no conflicts,I think.

**Comment by lowang-bh** [comment]
> > @lowang-bh I merged your PR #3064, you need to refresh this PR.
> 
> Hi, @william-wang , this PR is already based from #3064. There will be no conflicts,I think.

Have rebased from master.

**Comment by lowang-bh** [comment]
Hi, @william-wang , any update on this PR?

**Review by william-wang — APPROVED** [review]
/approve
