### PR TITLE
Fix unexpected regex validation on highestTierName in Volcano Job spec

### LINKED ISSUE #5233: Bug: Unexpected regex validation added to highestTierName in Volcano Job spec
### Description

A regex validation constraint is unexpectedly added to the highestTierName field in the Volcano Job specification, which is inconsistent with the expected functionality and breaks legitimate usage of this field.

### Steps to reproduce the issue

1. Submit a volcano job that sets highestTierName to "volcano.sh/hyperNode".

### Describe the results you received and expected

**Expected behavior**
The job is successfully created.

**Received behavior**
The job is intercepted by the admission webhook, because the highestTierName fails to match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'.

### What version of Volcano are you using?

1.14

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by Tau721**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR removes the unexpected regex validation (i.e., `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`) from the highestTierName field in the Volcano Job specification, and for the sake of consistency, adds the maxLength validation on the highestTierName field in the PodGroup specification. 

#### Which issue(s) this PR fixes:

Fixes #5233

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
For compatibility considerations, the regular expression validation for highestTierName, i.e.,  `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`,  is removed.  Now, users can specify highestTierName to any string with up to 253 characters.
```

### CODE REVIEW

File: staging/src/volcano.sh/apis/pkg/apis/scheduling/types.go [hunk 1]
```diff
@@ -270,6 +270,7 @@ type NetworkTopologySpec struct {
 
 	// HighestTierName specifies the highest tier name that a job allowed to cross when scheduling.
 	// HighestTierName and HighestTierAllowed cannot be set simultaneously.
+	// +kubebuilder:validation:MaxLength=253
```
[the remark this answers is not in the document]
Comment (Tau721) [reply staging/src/volcano.sh/apis/pkg/apis/scheduling/types.go:273]: Actually, the versioned API definition already has it.

File: installer/volcano-development-vap.yaml [hunk 2]
```diff
@@ -8920,6 +8916,15 @@ data:
   volcano-controller.conf: |
 ---
 # Source: volcano/templates/controllers.yaml
+apiVersion: v1
```
Comment (hajnalmt) [inline installer/volcano-development-vap.yaml:8919]: Something is messed up here. Why does the vap containing this configmap now? Did we miss something on master?

**Review by hajnalmt — COMMENTED** [review]
/label tide/merge-method-squash
/area controllers

Thanks. Why do we have the Sharding Configmap change here? Do we really need that?

File: installer/volcano-development-vap.yaml (hunk 2 above)
Comment (Tau721) [reply installer/volcano-development-vap.yaml:8919]: These are added after I run `make update-development-yaml TAG=latest`. I have no idea about it now.
