### PR TITLE
fix(event): fix FailedScheduling message might inaccurate when podgroup is ready

### LINKED ISSUE #4971: The scheduling reason is inaccurate
### Description

I describe the pod and read the message, find the content is strategy.

The podgroup status is Running
```
spark-d6ffce57e1834d76a0c805649f420262-podgroup   Running   1           7          11h
```

but in the pod event the podgroup is not ready
```
Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 7 Running, 89 Pending; Pending: 89 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 7 Running, 75 Pending; Pending: 75 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 67 Pending, 7 Running; Pending: 67 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 43 Pending, 7 Running; Pending: 43 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 42 Pending, 7 Running; Pending: 42 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 41 Pending, 7 Running; Pending: 41 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 39 Pending, 7 Running; Pending: 39 Unschedulable
  Warning  FailedScheduling  34m (x2 over 34m)     volcano  pod group is not ready, 1 minAvailable, 40 Pending, 7 Running; Pending: 40 Unschedulable
  Warning  FailedScheduling  34m                   volcano  pod group is not ready, 1 minAvailable, 46 Pending, 7 Running; Pending: 46 Unschedulable
  Warning  FailedScheduling  34m (x9 over 34m)     volcano  (combined from similar events): pod group is not ready, 1 minAvailable, 7 Running, 94 Pending; Pending: 94 Unschedulable
  Warning  FailedScheduling  5m34s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 92 Pending; Pending: 92 Unschedulable
  Warning  FailedScheduling  5m32s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 91 Pending; Pending: 91 Unschedulable
  Warning  FailedScheduling  5m30s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 89 Pending; Pending: 89 Unschedulable
  Warning  FailedScheduling  5m27s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 88 Pending; Pending: 88 Unschedulable
  Warning  FailedScheduling  5m26s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 87 Pending; Pending: 87 Unschedulable
  Warning  FailedScheduling  5m24s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 85 Pending; Pending: 85 Unschedulable
  Warning  FailedScheduling  5m22s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 84 Pending; Pending: 84 Unschedulable
  Warning  FailedScheduling  5m20s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 83 Pending; Pending: 83 Unschedulable
  Warning  FailedScheduling  5m17s                 volcano  pod group is not ready, 1 minAvailable, 7 Running, 81 Pending; Pending: 81 Unschedulable
  Warning  FailedScheduling  27s (x47 over 5m15s)  volcano  (combined from similar events): pod group is not ready, 1 minAvailable, 18 Pending, 7 Running; Pending: 18 Unschedulable
```

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

todo:

### What version of Volcano are you using?

master

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by ruanwenjun**
#### What type of PR is this?
bug fix
#### What this PR does / why we need it:

Fix the message print pod group is not ready when podgorup is already running.
```
Events:
  Type     Reason                  Age   From                  Message
  ----     ------                  ----  ----                  -------
  Warning  FailedScheduling        13m   volcano               pod group is ready, 1 minAvailable, 8 Running, 83 Pending; Pending: 83 Unschedulable
  Normal   AddEkletNodeToleration  13m   admission-controller  Successfully add eklet node toleration
  Warning  FailedScheduling        103s  volcano               pod group is ready, 1 minAvailable, 52 Pending, 8 Running; Pending: 52 Unschedulable
  Warning  FailedScheduling        82s   volcano               pod group is ready, 1 minAvailable, 51 Pending, 8 Running; Pending: 51 Unschedulable
  Warning  FailedScheduling        75s   volcano               pod group is ready, 1 minAvailable, 50 Pending, 8 Running; Pending: 50 Unschedulable
  Warning  FailedScheduling        40s   volcano               pod group is ready, 1 minAvailable, 49 Pending, 8 Running; Pending: 49 Unschedulable
  Warning  FailedScheduling        22s   volcano               pod group is ready, 1 minAvailable, 47 Pending, 8 Running; Pending: 47 Unschedulable
  Warning  FailedScheduling        14s   volcano               pod group is ready, 1 minAvailable, 46 Pending, 8 Running; Pending: 46 Unschedulable
```

#### Which issue(s) this PR fixes:
Fixes #4971

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/api/job_info.go [hunk 1]
```diff
@@ -771,8 +771,16 @@ func (ji *JobInfo) FitError() string {
...
-	reasonMsg := fmt.Sprintf("%v, %v", scheduling.PodGroupNotReady, strings.Join(sortReasonsHistogram(reasons), ", "))
+	minAvailable := int(ji.MinAvailable)
+	reasons["minAvailable"] = minAvailable
+
+	podGroupStatus := scheduling.PodGroupNotReady
+	if runningPod, ok := reasons[Running.String()]; ok {
+		if runningPod >= minAvailable {
+			podGroupStatus = scheduling.PodGroupReady
+		}
+	}
```
[the remark this answers is not in the document]
Comment (ruanwenjun) [reply pkg/scheduler/api/job_info.go:779]: done

File: pkg/scheduler/api/job_info.go [hunk 2]
```diff
@@ -771,8 +771,14 @@ func (ji *JobInfo) FitError() string {
 	for status, taskMap := range ji.TaskStatusIndex {
 		reasons[status.String()] += len(taskMap)
 	}
-	reasons["minAvailable"] = int(ji.MinAvailable)
-	reasonMsg := fmt.Sprintf("%v, %v", scheduling.PodGroupNotReady, strings.Join(sortReasonsHistogram(reasons), ", "))
+	minAvailable := int(ji.MinAvailable)
```
Comment (hajnalmt) [inline pkg/scheduler/api/job_info.go]: I am not sure that wether we need to take Bound, Binding and Allocated into the consideration too maybe... ReadyTaskNum condiders these too so maybe it is more appropriate:
```
podGroupStatus := scheduling.PodGroupNotReady
if ji.ReadyTaskNum() >= ji.MinAvailable {
    podGroupStatus = scheduling.PodGroupReady
}
```

Comment (hajnalmt) [reply pkg/scheduler/api/job_info.go]: The IsReady counts besteffort tasks too. Maybe that's the way:
```
podGroupStatus := scheduling.PodGroupNotReady
if ji.IsReady() {
    podGroupStatus = scheduling.PodGroupReady
}
```
But the Warnings will still be there, so this is just some cosmetics right?

Comment (ruanwenjun) [reply pkg/scheduler/api/job_info.go]: Done.
Yes, this PR only fix the message in the event, and the warning event still exist, I will take a look how to reduce the event, these kind of event don't need to exist in task events.

Comment (hajnalmt) [reply pkg/scheduler/api/job_info.go]: Thank you!

Comment (hajnalmt) [inline pkg/scheduler/api/job_info.go]: The `reasons["minAvailable"] = minAvailable`  can be changed back to `reasons["minAvailable"] = int(ji.MinAvailable)` now since we don't use the `minAvailable` variable elsewhere now.

Comment (ruanwenjun) [reply pkg/scheduler/api/job_info.go]: Thanks, done.

**Review by hajnalmt — APPROVED** [review]
/lgtm

Thank you for the contribution!

**Comment by JesseStutler** [comment]
/approve
Thanks!
