### PR TITLE
fix/feat(capacity):  AddReclaimableFn refactor

### LINKED ISSUE #4918: Various bugs/enhancement requests in the reclaimableFn in the capacity plugin
### Description

For starters let's see the current implementation:

https://github.com/volcano-sh/volcano/blob/0c6f3bf706ad6790b1e806ef5e65c2ffdb3418ba/pkg/scheduler/plugins/capacity/capacity.go#L105-L133

#### Bug 1: Reclaimer Resource Dimension Ignored

The reclaimableFn currently ignores the actual resource dimensions requested by the reclaimer.

It expects it as a parameter but does not use it in the function at all:
https://github.com/volcano-sh/volcano/blob/v1.13.1/pkg/scheduler/plugins/capacity/capacity.go#L105

The linters are not responding to this bug because in the klog output we use the reclaimer variable:
https://github.com/volcano-sh/volcano/blob/v1.13.1/pkg/scheduler/plugins/capacity/capacity.go#L131
https://github.com/volcano-sh/volcano/blob/0c6f3bf706ad6790b1e806ef5e65c2ffdb3418ba/pkg/scheduler/plugins/capacity/capacity.go#L131

Translating this means that the function is overselective regarding the `reclaimees`. Even when the `reclaimer` has no intersecting resource dimension with the `reclaimee` we will be reclaiming it.
Yes, we are evicting pods in the reclaiming process, even though it doesn't help to free up actual resources for the `reclaimer`.

#### Enhancement 1: Improve Victim Selection

The latter bug implies an enhancement idea regarding the `reclaimee-deserved` check.

If a `reclaimee` does not intersect with the queue's `deserved` resources but does intersect with the `reclaimer`, it should be considered a victim without further checks.

#### Enhancement 2: Logging and Comments

The victim selection process lacks sufficient logging and comments, making it difficult to understand and debug. (I went errands on this.)
This is mainly the reason why the bugs are hard to track here.

We just have a log line about the selected victims at the end of the function https://github.com/volcano-sh/volcano/blob/v1.13.1/pkg/scheduler/plugins/capacity/capacity.go#L131 and that's all.

To understand what's the purpose of allocated/allocations in this function is mind-throttling:
https://github.com/volcano-sh/volcano/blob/v1.13.1/pkg/scheduler/plugins/capacity/capacity.go#L120

#### Bug 2: Incorrect Use of LessEqual

As @zhifei92 correctly points out in the PR: https://github.com/volcano-sh/volcano/pull/4893.

LessEqual is used wrongfully in:
https://github.com/volcano-sh/volcano/blob/v1.13.1/pkg/scheduler/plugins/capacity/capacity.go#L125

If the allocated part in this comparision doesn't have a resource dimension but deserved has it, we will incorrectly assume that every task in the queue is a reclaimee.

#### Bug 3/Enhancement 3: Scalar-Only Queues are Not Supported yet from reclaiming perspective

There were already requests to be able to define Queues without `cpu` and `memory` in volcano in `deserved`. This is not possible yet from the capacity plugin's reclaiming perspective.

##### Resource API problem description
The current resource API in volcano does not allow us to define a resource actually without `cpu` or `memory`:
https://github.com/volcano-sh/volcano/blob/0c6f3bf706ad6790b1e806ef5e65c2ffdb3418ba/pkg/scheduler/api/resource_info.go#L58-L69

The scalar resources are handled as map so we can check if a scalar resource dimension with `name` exists in `r` resource with:
```
_, ok := r.ScalarResources[name]
```

On the other hand `r.MilliCPU` will return 0 if you define an `r := api.EmptyResource()` since it's go's default value for float64.
This is the reason why if we create a queue (just create a queue), it will not report scalar resources as allocated but `cpu` and `memory` as 0:

`kubectl get queues default -o yaml`
```bash
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: default
spec:
  guarantee: {}
  parent: root
  reclaimable: true
  weight: 1
status:
  allocated:
    cpu: "0"
    memory: "0"
  reservation: {}
  state: Open
``` 
This is probably historical, since we had `cpu` and `memory` dimensions first and appended scalar resources later on.

##### Why does this matter?

We cannot define the `deserved` part of a queue without CPU and Memory in volcano because every pod in the queue will be considered as a `reclaimee` as in Bug2.

This comes from the problem that the `allocated.LessEqual(attr.deserved, api.Infinity)` comparision won't actually compare these dimensions to be `Infinity` when they are not defined. We want in this comparision the `cpu` and `memory` dimensions to be disregarded like the scalars to support such queues.

This is currently not possible in our resource representation, see:
https://github.com/volcano-sh/volcano/blob/v1.13.1/pkg/scheduler/api/resource_info.go#L409
https://github.com/volcano-sh/volcano/blob/0c6f3bf706ad6790b1e806ef5e65c2ffdb3418ba/pkg/scheduler/api/resource_info.go#L409

And I came to the conclusion that it shouldn't be, we can create a new resources API or live with this and come up with a hacky workaround for this special case.

#### Documentation Updates

- [x] This feature requires design or user documentation changes.
- [x] If documentation changes are required, I will ensure the relevant documents are updated and published to the Volcano official website (https://volcano.sh) via the [volcano-sh/website](https://github.com/volcano-sh/website) repository.

##### PRs to solve the issue:
-  [ ] As an initial step we shall have the proper resource comparision logic implemented:
    -  https://github.com/volcano-sh/volcano/pull/4927
- [ ] Add unit tests for these issues.
    -  Second commit of: https://github.com/volcano-sh/volcano/pull/4919
- [ ] Based on the defined resource comparision logic we can fix the bugs.
    -  First commit of: https://github.com/volcano-sh/volcano/pull/4919
- [ ] Update the documentation about the new capability of the plugin.

### PR DESCRIPTION
**Pull request by hajnalmt**
This PR is based on https://github.com/volcano-sh/volcano/pull/4927 which adds the resources functions to enable the fix for all the issues mentioned in https://github.com/volcano-sh/volcano/issues/4918.

#### AddReclaimableFn refactor
The refactor itself is quite dense and squashed into this commit: https://github.com/volcano-sh/volcano/pull/4919/commits/d496505d92e79d40aa4046fec3881cd2728bf27f

It contains every bugs/enhancement mentioned in https://github.com/volcano-sh/volcano/issues/4918.
Namely the commit:
- Fixes reclaimableFn to properly consider the reclaimer's resource dimensions when selecting victims, preventing ineffective preemption
- Improves victim selection logic: if a reclaimee intersects with the reclaimer but not with the queue's deserved resources, it is immediately considered a victim.
- Adds detailed logging and comments to the victim selection process for better traceability and maintainability.
- Corrects the use of `LessEqual` by switching to `GreaterPartlyWithRelevantDimensions` in the resource comparison to avoid incorrectly marking all tasks as reclaimable when `allocated` resources lack dimensions present in `deserved`. Corrects the use of LessEqual in resource comparison to avoid marking all tasks as reclaimable when `allocated` resources lack dimensions present in `deserved`.
- Levaraging the new `GreaterPartlyWithRelevantDimensions` function. The bug/feature that prevented the scalar-only queues reclaim support is fixed too.

#### Capacity plugin new unit tests.
The PR contains carefully crafted unit tests for each bug in https://github.com/volcano-sh/volcano/issues/4918 squashed into the commit: https://github.com/volcano-sh/volcano/pull/4919/commits/db48e5a0fd522abb4fdad32f539e7111d4f6cfda
Each of them fails before the fixes:

`go test -v  -count=1  ./pkg/scheduler/plugins/capacity`
```bash
--- FAIL: Test_capacityPlugin_OnSessionOpenWithoutHierarchy (4.73s)
    --- PASS: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case0:_Pod_allocatable_when_queue_has_not_exceed_capability (0.47s)
    --- PASS: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case1:_Pod_not_allocatable_when_queue_exceed_queue_capability (0.45s)
    --- PASS: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case2:_Can_reclaim_from_other_queues_when_allocated_<_deserved (0.45s)
 ...
     --- PASS: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case6:_Can_not_reclaim_from_other_queues_when_allocated_+_req_>_deserved (0.45s)
    --- FAIL: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case7:_allocated_does_not_contain_scalar_dimension_(GPU),_deserved_does;_should_not_reclaim (0.40s)
    --- FAIL: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case8:_reclaimer_dimensions_are_considered_properly_while_evicting_reclaimees (0.70s)
    --- FAIL: Test_capacityPlugin_OnSessionOpenWithoutHierarchy/case9:_reclaimee_has_intersecting_scalar_dimensions_with_deserved_shouldn't_be_reclaimed_on_
...
FAIL
FAIL    volcano.sh/volcano/pkg/scheduler/plugins/capacity       12.613s
FAIL
 ```
 
 The test case bug coverage is follows:
  - case 7 covers Bug 2
  - case 8 covers Bug 1 and enhancement 1
  - case 9 covers Bug 3 / Enhancement 3   

I want to mention that case 8 fails flakyly with the old code because sometimes `p26` and sometimes `p28` are selected as victims by the plugin since the iteration on the `node.Tasks` map is not guaranteed in the reclaim action so the `reclaimee` array order varies too.

#### What type of PR is this?
/kind bug
/kind rfe

#### What this PR does / why we need it:
I added a detailed description about the problems and enhancements we need here:
https://github.com/volcano-sh/volcano/issues/4918

#### Which issue(s) this PR fixes:

Fixes #4918

#### Special notes for your reviewer:
Review the commits one by one, or generally start with https://github.com/volcano-sh/volcano/pull/4927

#### Does this PR introduce a user-facing change?

```release-note
fix(reclaim): capacity plugin selected not valid victims in the reclaim process due to bad resource comparision
feat(reclaim): the capacity plugin reclaim process now supports queues with only scalar resource dimensions on deserved
```

### CODE REVIEW

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 1]
```diff
@@ -867,6 +906,59 @@ func queueAllocatable(attr *queueAttr, candidate *api.TaskInfo, queue *api.Queue
 	return allocatable
 }
 
+// queueReclaimableForRequest checks if a queue is reclaimable based on the reclaimer's requested dimensions.
+// Returns true if reclaimable, along with the list of dimensions that are reclaimable, else false and empty list.
+// The thorough check is needed because we don't have a proper way to say that we don't care about
+// deserved CPU or Memory when the user not specifies it.
+func queueReclaimableForRequest(attr *queueAttr, allocated *api.Resource, req *api.TaskInfo) (bool, []string) {
```
[the remark this answers is not in the document]
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Ok, removed.

File: pkg/scheduler/plugins/capacity/capacity_test.go [hunk 2]
```diff
@@ -40,6 +41,10 @@ import (
 
 func TestMain(m *testing.M) {
 	options.Default()
+	// Change klog log level to new value
+	var logLevel klog.Level
+	logLevel.Set("2")
```
[the remark this answers is not in the document]
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity_test.go]: This was an accident removed.

File: pkg/scheduler/api/resource_info.go [hunk 3]
```diff
@@ -873,6 +873,26 @@ func (r ResourceNameList) Contains(rr ResourceNameList) bool {
...
+	nameSet := map[v1.ResourceName]struct{}{}
+	for _, name := range r1Names {
+		nameSet[name] = struct{}{}
+	}
+	for _, name := range r2Names {
+		if _, exists := nameSet[name]; exists {
+			// Only include if non-zero in both resources
+			if r1.Get(name) >= minResource && r2.Get(name) >= minResource {
+				intersection = append(intersection, name)
+			}
```
[the remark this answers is not in the document]
Comment (hajnalmt) [reply pkg/scheduler/api/resource_info.go]: True, modified ty.

**Comment by JesseStutler** [comment]
Could we divide this pr into several different prs to fix the bugs you mentioned in #4918? I think the current PR carried on too many bug fixes and it's hard to review it together

**Comment by hajnalmt** [comment]
/cc @JesseStutler @guoqinwill @hzxuzhonghu @dafu @zhifei92

I think this looks good now, and I managed fix the bugs here. Can someone help me with a review here?
I tried to divide into two PR-s so we can start with this one: https://github.com/volcano-sh/volcano/pull/4927

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 4]
```diff
@@ -113,22 +114,61 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
...
-			// When scalar resource not specified in deserved such as "pods", we should skip it and consider it as infinity,
-			// so the following first condition will be true and the current queue will not be reclaimed.
-			if allocated.LessEqual(attr.deserved, api.Infinity) || !attr.guarantee.LessEqual(exceptReclaimee, api.Zero) {
+			reclaimable = attr.guarantee.LessEqual(exceptReclaimee, api.Zero)
+			if !reclaimable {
+				continue
+			}
+
+			// If the reclaimee has no intersecting resource dimensions with deserved, it is a victim.
+			deservedIntersecting := len(api.Intersection(reclaimee.Resreq, attr.deserved)) > 0
```
Comment (JesseStutler) [inline pkg/scheduler/plugins/capacity/capacity.go]: I'm wondering that will we meet such case? `reclaimee` is already allocated resources, so it should contains intersected resources with deserved.

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 5]
```diff
@@ -113,22 +114,61 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
...
+				klog.V(5).Infof("No intersection between deserved: %v and reclaimee <%s/%s>. It's a victim."+
+					" Current victims: %+v.", attr.deserved, reclaimee.Namespace, reclaimee.Name, victims)
 				continue
 			}
+
+			// Check deserved
+			reclaimable, dims := allocated.GreaterPartlyWithRelevantDimensions(attr.deserved, reclaimee.Resreq)
+			if !reclaimable {
+				klog.V(5).Infof("Queue <%v>	is not reclaimable for reclaimer <%s/%s>: "+
+					"deserved: <%v>, allocated: <%v>, reclaimee <%s/%s> Resreq: <%v>.",
```
Comment (JesseStutler) [inline pkg/scheduler/plugins/capacity/capacity.go]: We can add more log info to tell users that allocated has already greater than deserved and can't continually be reclaimed

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 4 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Actually this is the mostly used case, as `deserved` is optional in the queue API, so when we create a queue (without deserved), every pod in the queue will be a reclaimee for other queues due to this check. `reclaimee` intersects with `allocated` on every dimension of `reclaimee` of course, maybe that's the confusing part here?

Also if you create a scalar-only queue I mean deserved(0 cpu, 0 memory, gpu:1) and you have a pure CPU/Memory pod in that queue, this check will enable this pod to be reclaimed by other queues.

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 5 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: true, will do it ty!

Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: At this point the queue maybe still be reclaimable for reclaimer, only the reclaimee is not a victim. I modified the log to this one:
```
				klog.V(5).Infof(
					"Queue <%v> allocated resources are not greater than deserved on any relevant dimension of reclaimee. "+
						"Hence reclaimee <%s/%s> cannot be reclaimed for reclaimer <%s/%s>. "+
						"Deserved: <%v>, Allocated: <%v>, Reclaimee Resreq: <%v>. ",
					attr.name, reclaimee.Namespace, reclaimee.Name, reclaimer.Namespace, reclaimer.Name, attr.deserved, allocated, reclaimee.Resreq,
				)
```
What do you think?

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 6]
```diff
@@ -113,22 +114,64 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
 		for _, reclaimee := range reclaimees {
 			job := ssn.Jobs[reclaimee.Job]
 			attr := cp.queueOpts[job.Queue]
+			klog.V(5).Infof("Considering reclaimee <%s/%s> from queue <%s> for reclaimer <%s/%s>.",
+				reclaimee.Namespace, reclaimee.Name, attr.queueID, reclaimer.Namespace, reclaimer.Name)
+			reclaimable := false
+
+			// If reclaimee doesn't have intersecting resource dimensions with reclaimer we can skip it.
+			reclaimerIntersecting := len(api.IntersectionWithIgnoredScalarResources(reclaimee.Resreq, reclaimer.Resreq)) > 0
```
Comment (hajnalmt) [inline pkg/scheduler/plugins/capacity/capacity.go]: Hmm, I am wondering if it's more precise to use `reclaimer.InitResreq` instead of `reclaimer.Resreq` everywhere in this function...

Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: It is more precise, modified the commit to use InitResreq.

**Comment by hajnalmt** [comment]
/cc @guoqinwill
/priority high

Can you help me to review this too guoqinwill?

**Comment by hajnalmt** [comment]
Maybe @dafu-wu can help in the review here too.

@JesseStutler @hzxuzhonghu
Applied every change on this branch too so we have examples on the resource functions and the logging is more straightforward.
One additional change is that I modified the use of `reclaimer.Resreq` to `reclaimer.InitResreq` to be precise.

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 5 above)
Comment (JesseStutler) [reply pkg/scheduler/plugins/capacity/capacity.go]: Yes I think it's great!

**Comment by guoqinwill** [comment]
> /cc @guoqinwill /priority high 
> 
> Can you help me to review this too guoqinwill?

Okay, thank you for your submission. I've been a bit busy with personal work these past few days, but I will take a look at it later.

**Comment by hajnalmt** [comment]
Thank you, updated the description and rebased the PR on top of https://github.com/volcano-sh/volcano/pull/4927 !
Please review again 👍

**Comment by hajnalmt** [comment]
Thank you, updated the description and rebased the PR now on master!
Please review ☺️

**Comment by dafu-wu** [comment]
> Maybe @dafu-wu can help in the review here too.
> 
> @JesseStutler @hzxuzhonghu Applied every change on this branch too so we have examples on the resource functions and the logging is more straightforward. One additional change is that I modified the use of `reclaimer.Resreq` to `reclaimer.InitResreq` to be precise.

Thanks for looping me in. I’ll review and provide comments shortly.

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 7]
```diff
@@ -113,22 +114,64 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
 		for _, reclaimee := range reclaimees {
 			job := ssn.Jobs[reclaimee.Job]
 			attr := cp.queueOpts[job.Queue]
+			klog.V(5).Infof("Considering reclaimee <%s/%s> from queue <%s> for reclaimer <%s/%s>.",
+				reclaimee.Namespace, reclaimee.Name, attr.queueID, reclaimer.Namespace, reclaimer.Name)
+			reclaimable := false
+
+			// If reclaimee doesn't have intersecting resource dimensions with reclaimer we can skip it.
+			reclaimerIntersecting := len(api.IntersectionWithIgnoredScalarResources(reclaimee.Resreq, reclaimer.InitResreq)) > 0
```
Comment (dafu-wu) [inline pkg/scheduler/plugins/capacity/capacity.go]: * Refactored as:
`func (cp *capacityPlugin) shouldSkipReclaimee(reclaimee, reclaimer *api.TaskInfo) (bool, string) {...}`

* Simplified as:
```
   if skip, reason := cp.shouldSkipReclaimee(reclaimee, reclaimer); skip {
       klog.V(5).Infof("%s, skip it.", reason)
       continue
   }
```

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 8]
```diff
@@ -113,22 +114,64 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
...
 				allocations[job.Queue] = attr.allocated.Clone()
 			}
 			allocated := allocations[job.Queue]
 
+			// Check guarantee
 			exceptReclaimee := allocated.Clone().Sub(reclaimee.Resreq)
-			// When scalar resource not specified in deserved such as "pods", we should skip it and consider it as infinity,
-			// so the following first condition will be true and the current queue will not be reclaimed.
-			if allocated.LessEqual(attr.deserved, api.Infinity) || !attr.guarantee.LessEqual(exceptReclaimee, api.Zero) {
+			reclaimable = attr.guarantee.LessEqual(exceptReclaimee, api.Zero)
```
Comment (dafu-wu) [inline pkg/scheduler/plugins/capacity/capacity.go]: * refactored as?
```
func (cp *capacityPlugin) checkGuaranteeConstraint(
       allocated *api.Resource, 
       reclaimee *api.TaskInfo, 
       guarantee *api.Resource,
   ) (bool, *api.Resource) {...}
```
   
* Simplfied as:
```
      if satisfies, _ := cp.checkGuaranteeConstraint(allocated, reclaimee, attr.guarantee); !satisfies {
       continue
   }
```

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 9]
```diff
@@ -113,22 +114,64 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
...
+			if !reclaimable {
+				continue
+			}
+
+			// If the reclaimee has no intersecting resource dimensions with deserved, it is a victim.
+			deservedIntersecting := len(api.Intersection(reclaimee.Resreq, attr.deserved)) > 0
+			if !deservedIntersecting {
```
Comment (dafu-wu) [inline pkg/scheduler/plugins/capacity/capacity.go]: * Refactore as:
```
   func (cp *capacityPlugin) isImmediateVictim(
       reclaimee *api.TaskInfo,
       deserved *api.Resource,
   ) (bool, string) {...}
```
* Simplified usage:
```
   if isVictim, reason := cp.isImmediateVictim(reclaimee, attr.deserved); isVictim {
       allocated.Sub(reclaimee.Resreq)
       victims = append(victims, reclaimee)
       klog.V(5).Infof("%s. It's a victim. Current victims: %+v.", reason, victims)
       continue
   }
```

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 10]
```diff
@@ -113,22 +114,64 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
...
+				allocated.Sub(reclaimee.Resreq)
+				victims = append(victims, reclaimee)
+				klog.V(5).Infof("No intersection between deserved: %v and reclaimee <%s/%s>. It's a victim."+
+					" Current victims: %+v.", attr.deserved, reclaimee.Namespace, reclaimee.Name, victims)
 				continue
 			}
+
+			// Check deserved
+			reclaimable, dims := allocated.GreaterPartlyWithRelevantDimensions(attr.deserved, reclaimee.Resreq)
```
Comment (dafu-wu) [inline pkg/scheduler/plugins/capacity/capacity.go]: Refactored as:
```
   func (cp *capacityPlugin) checkDeservedExceedance(
       allocated *api.Resource,
       deserved *api.Resource,
       reclaimee *api.TaskInfo,
       reclaimer *api.TaskInfo,
       queueName string,
   ) (bool, []string, string) {}
```
   * Simplified as:
   
```
      if exceeds, dims, reason := cp.checkDeservedExceedance(
       allocated, attr.deserved, reclaimee, reclaimer, attr.name); !exceeds {
       klog.V(5).Infof("%s", reason)
       continue
   }
```

File: pkg/scheduler/plugins/capacity/capacity.go [hunk 11]
```diff
@@ -113,22 +114,64 @@ func (cp *capacityPlugin) OnSessionOpen(ssn *framework.Session) {
...
 			job := ssn.Jobs[reclaimee.Job]
 			attr := cp.queueOpts[job.Queue]
+			klog.V(5).Infof("Considering reclaimee <%s/%s> from queue <%s> for reclaimer <%s/%s>.",
+				reclaimee.Namespace, reclaimee.Name, attr.queueID, reclaimer.Namespace, reclaimer.Name)
+			reclaimable := false
+
+			// If reclaimee doesn't have intersecting resource dimensions with reclaimer we can skip it.
+			reclaimerIntersecting := len(api.IntersectionWithIgnoredScalarResources(reclaimee.Resreq, reclaimer.InitResreq)) > 0
+			if !reclaimerIntersecting {
+				klog.V(5).Infof("Reclaimee <%s/%s>: <%v> does not have intersecting resource dimensions with reclaimer <%s/%s>: <%v>, skip it.",
```
Comment (dafu-wu) [inline pkg/scheduler/plugins/capacity/capacity.go]:
```go
   // It is recommended to use a unified log format for easier parsing.
   klog.V(5).Infof("[Capacity] Reclaimee <%s/%s> skipped: no intersection with reclaimer <%s/%s>",
       reclaimee.Namespace, reclaimee.Name, reclaimer.Namespace, reclaimer.Name)
   ```

Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Hmm, I checked that we use this elsewhere too like in the `numaaware` plugin.
I am fine with it. I would prefer this lower cased `[capacity]` and touch only this only function now. Is that okay for you?

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 7 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Ty. Added the function!

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 8 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Ty. Added the function!

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 9 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Ty. Added the function!

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 10 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: Ty. Added the function!

File: pkg/scheduler/plugins/capacity/capacity.go (hunk 11 above)
Comment (hajnalmt) [reply pkg/scheduler/plugins/capacity/capacity.go]: I modified the code have [capacity] in each of the log messages.

**Comment by hajnalmt** [comment]
Thanks for the reviews @dafu-wu and @JesseStutler!
I believe I’ve addressed all the feedback.

While working on this, I noticed that the function comment for the `resource_info` functions wasn’t being highlighted correctly when I invoked the function. I added a small adjustment so that syntax highlighters can pick it up more reliably.

**Comment by dafu-wu** [comment]
/approve

Thanks @hajnalmt
