### PR TITLE
fix restart task/partition when pod evicted

### LINKED ISSUE #4814: A vcjob with the policy "RestartTask when PodEvicted" does not behave as expected when the pod is evicted
### Description

A vcjob with the policy "RestartTask when PodEvicted" does not behave as expected when the pod is evicted.
The policy "RestartPartition when PodEvicted" has the same issue.

### Steps to reproduce the issue

1. Create a vcjob with `policies` as follows:
   ```
   task0:
   	vjtest-task0-0
   	vjtest-task0-1
   task1:
   	partition0:
   		vjtest-task1-0
   		vjtest-task1-1
   	partition1:
   		vjtest-task1-2
   		vjtest-task1-3
   ```
   ```yaml
   apiVersion: batch.volcano.sh/v1alpha1
   kind: Job
   metadata:
     name: vjtest
   spec:
     schedulerName: volcano
     minAvailable: 1
     tasks:
       - name: "task0"
         replicas: 2
         policies:
           - action: RestartTask
             event: PodEvicted
         template:
           spec:
             containers:
               - name: container1
                 image: nginx
                 imagePullPolicy: IfNotPresent
             restartPolicy: Never
       - name: "task1"
         replicas: 4
         policies:
           - action: RestartPartition
             event: PodEvicted
         partitionPolicy:
           totalPartitions: 2
           partitionSize: 2
           networkTopology:
             mode: hard
             highestTierAllowed: 1
         template:
           spec:
             containers:
               - name: container1
                 image: nginx
                 imagePullPolicy: IfNotPresent
             restartPolicy: Never
   ```
   The scheduling result is as follows, all pods are running:
   ```shell
   # kubectl get po
   NAME             READY   STATUS    RESTARTS   AGE
   vjtest-task0-0   1/1     Running   0          5s
   vjtest-task0-1   1/1     Running   0          5s
   vjtest-task1-0   1/1     Running   0          5s
   vjtest-task1-1   1/1     Running   0          5s
   vjtest-task1-2   1/1     Running   0          5s
   vjtest-task1-3   1/1     Running   0          5s
   ```
2. Kill one pod in task `task0`, the result is as follows:
   ```shell
   # kubectl delete po vjtest-task0-1
   pod "vjtest-task0-1" deleted from default namespace
   # kubectl get po
   No resources found in default namespace.
   # kubectl get vj
   NAME     STATUS   MINAVAILABLE   RUNNINGS   AGE
   vjtest   Failed   1                         14s
   ```
   The vcjob status changed to failed, so all pods were deleted.

### Describe the results you received and expected

The eviction of a pod should trigger the restart of the task it belongs to.

### What version of Volcano are you using?

master

### Any other relevant information
The status and events of vcjob are as follows:
```shell
# kubectl describe vj vjtest
...
Status:
  Conditions:
    Last Transition Time:  2025-12-15T12:28:03Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:04Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:05Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:07Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:07Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:08Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:08Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:08Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:08Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Restarting
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Restarting
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Pending
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Running
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Restarting
    Last Transition Time:  2025-12-15T12:28:18Z
    Status:                Failed
  Min Available:           1
  Retry Count:             3
  Running Duration:        15s
  State:
    Last Transition Time:  2025-12-15T12:28:18Z
    Phase:                 Failed
  Version:                 22
Events:
  Type     Reason         Age                From                   Message
  ----     ------         ----               ----                   -------
  Normal   ExecuteAction  22s (x4 over 22s)  vc-controller-manager  Start to execute action RestartTask
  Warning  PodGroupError  22s                vc-controller-manager  Failed to create PodGroup, err: podgroups.scheduling.volcano.sh "vjtest-d95e4746-3074-47ce-856f-34d314a0bda1" not found
```

The relevant logs are as follows
```shell
...
I1215 12:28:18.432174       1 job_controller.go:356] Try to handle request <Queue: , Job: default/vjtest, Task:task0, Pod:vjtest-task0-1, Event:PodEvicted, ExitCode:0, Action:, JobVersion: 0>
I1215 12:28:18.432203       1 job_controller.go:385] Execute <RestartTask> on Job <default/vjtest> in <Running> by <*state.runningState>.
I1215 12:28:18.432265       1 job_controller_actions.go:69] Killing task <task0> of Job <default/vjtest>, current version 0
I1215 12:28:18.432592       1 event.go:377] Event(v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"vjtest", UID:"d95e4746-3074-47ce-856f-34d314a0bda1", APIVersion:"batch.volcano.sh/v1alpha1", ResourceVersion:"21658", FieldPath:""}): type: 'Normal' reason: 'ExecuteAction' Start to execute action RestartTask
I1215 12:28:18.451478       1 job_controller_actions.go:224] Running duration is 15.451465998s
I1215 12:28:18.472913       1 garbagecollector.go:128] Updating job default/vjtest
I1215 12:28:18.478254       1 job_controller_actions.go:79] Finished task <task0> of Job <default/vjtest> killing, current version 0
I1215 12:28:18.478284       1 job_controller.go:356] Try to handle request <Queue: , Job: default/vjtest, Task:task0, Pod:vjtest-task0-0, Event:PodEvicted, ExitCode:0, Action:, JobVersion: 0>
I1215 12:28:18.478304       1 job_controller.go:385] Execute <RestartTask> on Job <default/vjtest> in <Restarting> by <*state.restartingState>.
I1215 12:28:18.478354       1 job_controller_actions.go:69] Killing task <task0> of Job <default/vjtest>, current version 0
I1215 12:28:18.478370       1 job_controller_actions.go:224] Running duration is 15.478366599s
I1215 12:28:18.478396       1 queue_controller.go:243] Begin execute SyncQueue action for queue default, current status Open
I1215 12:28:18.478415       1 queue_controller_action.go:49] Begin to sync queue default.
I1215 12:28:18.478434       1 queue_controller_action.go:112] End sync queue default.
I1215 12:28:18.478441       1 queue_controller.go:225] Finished syncing queue default (50.305µs).
I1215 12:28:18.478531       1 event.go:377] Event(v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"vjtest", UID:"d95e4746-3074-47ce-856f-34d314a0bda1", APIVersion:"batch.volcano.sh/v1alpha1", ResourceVersion:"21679", FieldPath:""}): type: 'Normal' reason: 'ExecuteAction' Start to execute action RestartTask
I1215 12:28:18.489428       1 garbagecollector.go:128] Updating job default/vjtest
I1215 12:28:18.489508       1 job_controller_actions.go:79] Finished task <task0> of Job <default/vjtest> killing, current version 0
I1215 12:28:18.489520       1 job_controller.go:356] Try to handle request <Queue: , Job: default/vjtest, Task:, Pod:, Event:OutOfSync, ExitCode:0, Action:, JobVersion: 0>
I1215 12:28:18.489580       1 job_controller.go:385] Execute <SyncJob> on Job <default/vjtest> in <Pending> by <*state.pendingState>.
I1215 12:28:18.489592       1 job_controller_actions.go:329] Starting to sync up Job <default/vjtest>, current version 0
I1215 12:28:18.489727       1 job_controller_actions.go:270] Starting to initiate Job <default/vjtest>
I1215 12:28:18.500940       1 job_controller_actions.go:404] Job <default/vjtest> has not updated for no changing
I1215 12:28:18.500960       1 job_controller_actions.go:405] Finished Job <default/vjtest> sync up, current version 0
I1215 12:28:18.500975       1 job_controller.go:356] Try to handle request <Queue: , Job: default/vjtest, Task:task0, Pod:vjtest-task0-1, Event:PodEvicted, ExitCode:0, Action:, JobVersion: 0>
I1215 12:28:18.501010       1 job_controller.go:385] Execute <RestartTask> on Job <default/vjtest> in <Pending> by <*state.pendingState>.
I1215 12:28:18.501027       1 job_controller_actions.go:69] Killing task <task0> of Job <default/vjtest>, current version 0
I1215 12:28:18.501026       1 queue_controller.go:243] Begin execute SyncQueue action for queue default, current status Open
I1215 12:28:18.501035       1 queue_controller_action.go:49] Begin to sync queue default.
I1215 12:28:18.501044       1 job_controller_actions.go:224] Running duration is 15.501040187s
I1215 12:28:18.501055       1 queue_controller_action.go:112] End sync queue default.
I1215 12:28:18.501058       1 queue_controller.go:225] Finished syncing queue default (39.388µs).
I1215 12:28:18.501305       1 event.go:377] Event(v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"vjtest", UID:"d95e4746-3074-47ce-856f-34d314a0bda1", APIVersion:"batch.volcano.sh/v1alpha1", ResourceVersion:"21683", FieldPath:""}): type: 'Normal' reason: 'ExecuteAction' Start to execute action RestartTask
I1215 12:28:18.512580       1 garbagecollector.go:128] Updating job default/vjtest
I1215 12:28:18.517745       1 job_controller_actions.go:79] Finished task <task0> of Job <default/vjtest> killing, current version 0
...
```
_No response_

### PR DESCRIPTION
**Pull request by ouyangshengjia**
#### What type of PR is this?
/kind bug
#### What this PR does / why we need it:
When a vcjob is configured with the policy `PodEvicted` -> `RestartTask`/`RestartPartition`, evicting a pod will trigger `RestartTask`/`RestartPartition`, which deletes all pods in that task/partition. The pods deleted this way then retrigger the restart action, causing repeated self-triggered restarts until the maximum retry limit is reached and the job enters the `Failed` status.

#### Which issue(s) this PR fixes:

Fixes #4814 

#### Special notes for your reviewer:
@wangyang0616 @JesseStutler 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```
#### After fixing:
create the vcjob:
```
task0:
	vjtest-task0-0
	vjtest-task0-1
task1:
	partition0:
		vjtest-task1-0
		vjtest-task1-1
	partition1:
		vjtest-task1-2
		vjtest-task1-3
```
```shell
# kubectl get po
NAME             READY   STATUS    RESTARTS   AGE
vjtest-task0-0   1/1     Running   0          5s
vjtest-task0-1   1/1     Running   0          5s
vjtest-task1-0   1/1     Running   0          5s
vjtest-task1-1   1/1     Running   0          5s
vjtest-task1-2   1/1     Running   0          5s
vjtest-task1-3   1/1     Running   0          5s
```

**Scenario 1: `PodEvicted` -> `RestartTask`**
Kill one pod in task `task0`, all pods in the task are restarted, and the **Retry Count** in vcjob status increases to 1.
```shell
# kubectl delete po vjtest-task0-1
pod "vjtest-task0-1" deleted from default namespace

# kubectl get po
NAME             READY   STATUS    RESTARTS   AGE
vjtest-task0-0   1/1     Running   0          6s
vjtest-task0-1   1/1     Running   0          6s
vjtest-task1-0   1/1     Running   0          18s
vjtest-task1-1   1/1     Running   0          18s
vjtest-task1-2   1/1     Running   0          18s
vjtest-task1-3   1/1     Running   0          18s

# kubectl describe vj vjtest
...
Status:
  ...
  Min Available:           1
  Retry Count:             1
  Running:                 6
  State:
    Last Transition Time:  2025-12-15T12:16:55Z
    Phase:                 Running
  Task Status Count:
    task0:
      Phase:
        Running:  2
    task1:
      Phase:
        Running:  4
Events:
  Type     Reason         Age   From                   Message
  ----     ------         ----  ----                   -------
  Normal   ExecuteAction  11s   vc-controller-manager  Start to execute action RestartTask
```

**Scenario 2: `PodEvicted` -> `RestartPartition`**
Kill one pod in task `task1` partion `partition1`, all pods in the partition are restarted, and the **Retry Count** in vcjob status increases to 2.
```shell
# kubectl delete po vjtest-task1-2
pod "vjtest-task1-2" deleted from default namespace

# kubectl get po
NAME             READY   STATUS    RESTARTS   AGE
vjtest-task0-0   1/1     Running   0          23s
vjtest-task0-1   1/1     Running   0          23s
vjtest-task1-0   1/1     Running   0          35s
vjtest-task1-1   1/1     Running   0          35s
vjtest-task1-2   1/1     Running   0          3s
vjtest-task1-3   1/1     Running   0          3s

# kubectl describe vj vjtest
...
Status:
  ...
  Min Available:           1
  Retry Count:             2
  Running:                 6
  State:
    Last Transition Time:  2025-12-15T12:17:15Z
    Phase:                 Running
  Task Status Count:
    task0:
      Phase:
        Running:  2
    task1:
      Phase:
        Running:  4
Events:
  Type     Reason         Age   From                   Message
  ----     ------         ----  ----                   -------
  Normal   ExecuteAction  31s   vc-controller-manager  Start to execute action RestartTask
  Normal   ExecuteAction  11s   vc-controller-manager  Start to execute action RestartPartition
```

### CODE REVIEW

File: pkg/controllers/job/job_controller_actions.go [hunk 1]
```diff
@@ -175,6 +176,18 @@ func (cc *jobcontroller) killPods(jobInfo *apis.JobInfo, podRetainPhase state.Ph
 		}
 	}
 
+	for _, pod := range podsToKill {
```
Comment (kingeasternsun) [inline pkg/controllers/job/job_controller_actions.go]: Why do we need to set pods `OutOfSync`  before deleting them?

Comment (kingeasternsun) [reply pkg/controllers/job/job_controller_actions.go]: I got it!

Comment (ouyangshengjia) [reply pkg/controllers/job/job_controller_actions.go]: The controller will receive pod eviction events triggered by the pods that were killed here. To prevent the restart action from being triggered again, I use the "OutOfSync" annotation to mark these pods and ignore events related to pods with this annotation.

File: pkg/controllers/job/job_controller_actions.go [hunk 2]
```diff
@@ -175,6 +176,18 @@ func (cc *jobcontroller) killPods(jobInfo *apis.JobInfo, podRetainPhase state.Ph
...
+		_, err := cc.kubeClient.CoreV1().Pods(pod.Namespace).Patch(context.TODO(), pod.Name, types.JSONPatchType,
+			jobhelpers.OutOfSyncJSONPatch(), metav1.PatchOptions{})
+		if err == nil || apierrors.IsNotFound(err) {
+			klog.V(3).InfoS("Marked Pod as out-of-sync", "Pod", klog.KObj(pod), "UID", pod.UID)
+			continue
+		} else {
+			// record the error, and then collect the pod info like retained pod
+			errs = append(errs, err)
+		}
+	}
```
[the remark this answers is not in the document]
Comment (JesseStutler) [reply pkg/controllers/job/job_controller_actions.go]: Make sense, please take a look @ouyangshengjia

[the remark this answers is not in the document]
Comment (ouyangshengjia) [reply pkg/controllers/job/job_controller_actions.go]: fixed

**Comment by JesseStutler** [comment]
/approve
/lgtm
Thanks!
