### PR TITLE
Fix: vNPU HAMi mode may not work with multi-type NPUs cluster

### LINKED ISSUE #4778: [Bug] when turn on deviceshare.AscendHAMiVNPUEnable, only one type of NPU will be scheduled
### Description

If a cluster has more than one type of NPU, eg. both Ascend910B3 and Ascend910B4 in same cluster.
Only workloads using certain NPU type will be scheduled, the pods using other NPUs will Pending forever

### Steps to reproduce the issue

1. prepared a cluster has more than one NPU type, in my case, i have two nodes:
  
    - NodeA: Ascend910B3 * 8
    - NodeB: Ascend910B4 * 8
    
    use volcano scheduler in master branch, and turned on vNPU HAMi mode according to this [doc](https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_vnpu.md)

2. prepared two workload
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: npu-test-deployment-A
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: npu-test
      template:
        metadata:
          labels:
            app: npu-test
        spec:
          containers:
          - name: finetune-training-container
            image: swr.cn-south-1.myhuaweicloud.com/ascendhub/ascend-pytorch:24.0.RC1-A2-1.11.0-ubuntu20.04
            imagePullPolicy: Always
            args: [ "sleep", "infinity" ]
            resources:
              limits:
                huawei.com/Ascend910B3: 1
                huawei.com/Ascend910B3-memory: 32768
          restartPolicy: Always
          schedulerName: volcano
    ```
    
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: npu-test-deployment-B
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: npu-test
      template:
        metadata:
          labels:
            app: npu-test
        spec:
          containers:
          - name: finetune-training-container
            image: swr.cn-south-1.myhuaweicloud.com/ascendhub/ascend-pytorch:24.0.RC1-A2-1.11.0-ubuntu20.04
            imagePullPolicy: Always
            args: [ "sleep", "infinity" ]
            resources:
              limits:
                huawei.com/Ascend910B4: 1
                huawei.com/Ascend910B4-memory: 32768
          restartPolicy: Always
          schedulerName: volcano
    ```
    these two deployments has same spec except card type

3. apply these yaml, only npu-test-deployment-B's pod (which use Ascend910B4) will pending forever.  
    After checking correlated podgroup's event, it show these warnings:
    ```bash
    ----     ------         ----                    ----     -------
    Normal   Unschedulable  24m (x2 over 24m)       volcano  resource in cluster is overused: overused huawei.com/Ascend910B4-memory
    Warning  Unschedulable  4m39s (x1186 over 24m)  volcano  1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable; Pending: 1 Unschedulable
    ```

### Describe the results you received and expected

The workload using NPUs other than Ascend910B3 will Pending forever.

And the warning in podgroup should not exist since ```huawei.com/Ascend910B4-memory``` should inside ignore list.

### What version of Volcano are you using?

latest

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by kiritoxkiriko**
#### What type of PR is this?
BugFix

#### What this PR does / why we need it:
vNPU HAMi mode may not work with multi-type NPUs cluster

#### Which issue(s) this PR fixes:

Fixes #4778 

#### Special notes for your reviewer:
According to the problem described in this issue #4778 
I address this bug should related with IgnoredDevicesList, since the ```${card_type}-memory``` resource should be ignored in scheduling.

After checking out the codes, I found out the old IgnoredDevicesList.Set method will refresh all of device in the list, which will be used for setting node resource

```go
// pkg/scheduler/api/node_info.go:345
// setNodeOthersResource initialize sharable devices
func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
	if node == nil {
		klog.Warningf("received argument of nil node, no need to set other resources for %s", ni.Name)
		return
	}

	ni.Others[gpushare.DeviceName] = gpushare.NewGPUDevices(ni.Name, node)
	ni.Others[vgpu.DeviceName] = vgpu.NewGPUDevices(ni.Name, node)
	ni.Others[vnpu.DeviceName] = vnpu.NewNPUDevices(ni.Name, node)
	ascend_ignored_list := []string{}
	for device_name, devices := range hami.NewAscendDevices(ni.Name, node) {
		ni.Others[device_name] = devices
		// only Devices for this node will add to ignore list
		ascend_ignored_list = append(ascend_ignored_list, devices.GetIgnoredDevices()...)
	}
	klog.V(5).Infof("ascend_ignored_list is %v", ascend_ignored_list)
	// IgnoredDevices will be set here,
	IgnoredDevicesList.Set(
		ni.Others[gpushare.DeviceName].(Devices).GetIgnoredDevices(),
		ni.Others[vgpu.DeviceName].(Devices).GetIgnoredDevices(),
		ni.Others[vnpu.DeviceName].(Devices).GetIgnoredDevices(),
		ascend_ignored_list,
	)
	klog.V(5).Infof("ignoredDevicesList is %v", IgnoredDevicesList.List())
}
```
```go
// pkg/scheduler/api/shared_device_pool.go:99

var IgnoredDevicesList = ignoredDevicesList{}

type ignoredDevicesList struct {
	sync.RWMutex
	ignoredDevices []string
}

// this method will set and refresh the list
func (l *ignoredDevicesList) Set(deviceLists ...[]string) {
	l.Lock()
	defer l.Unlock()
	l.ignoredDevices = l.ignoredDevices[:0]
	for _, devices := range deviceLists {
		l.ignoredDevices = append(l.ignoredDevices, devices...)
	}
}

```
Only one node's device will be ignore here, and we may have multiple nodes, but the `Set` method will refresh the list very time it calls, so the ignore list will only keep last evaluated node's device in the end. That's why only one kind of NPU mem will be ignore in this case.

I tried to keep the orignial IgnoredDevicesList functions, and add new methods in this commit, and also use map to keep the list items unique since we don't want add duplicated resource in this list

Please take a look @archlitchi 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/api/node_info.go [hunk 1]
```diff
@@ -356,12 +356,14 @@ func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
...
 		ascend_ignored_list = append(ascend_ignored_list, devices.GetIgnoredDevices()...)
 	}
-	IgnoredDevicesList.Set(
+	klog.V(5).Infof("ascend_ignored_list is %v", ascend_ignored_list)
+	IgnoredDevicesList.AppendList(
 		ni.Others[gpushare.DeviceName].(Devices).GetIgnoredDevices(),
 		ni.Others[vgpu.DeviceName].(Devices).GetIgnoredDevices(),
 		ni.Others[vnpu.DeviceName].(Devices).GetIgnoredDevices(),
 		ascend_ignored_list,
 	)
```
[the remark this answers is not in the document]
Comment (kiritoxkiriko) [reply pkg/scheduler/api/node_info.go:380]: i think this issue is ok? since these ignored resource will not be use in anywhere else.

**Comment by archlitchi** [comment]
please sign-off your commit to pass the DCO check

File: pkg/scheduler/api/node_info.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (archlitchi) [reply pkg/scheduler/api/node_info.go:380]: you can resolve this manually if neglectable.

File: pkg/scheduler/api/shared_device_pool.go [hunk 2]
```diff
@@ -96,19 +96,68 @@ func RegisterDevice(deviceName string) {
 	RegisteredDevices = append(RegisteredDevices, deviceName)
 }
 
-var IgnoredDevicesList = ignoredDevicesList{}
+var IgnoredDevicesList = newIgnoredDevicesList()
 
 type ignoredDevicesList struct {
 	sync.RWMutex
 	ignoredDevices []string
+	ignoredIndex   map[string]struct{}
```
Comment (archlitchi) [inline pkg/scheduler/api/shared_device_pool.go]: what is this field used for? If only to avoid duplication, we can use Slice.contains() instead of adding a separate 'ignoredIndex' field

File: pkg/scheduler/api/node_info.go [hunk 3]
```diff
@@ -356,12 +356,14 @@ func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
 		ni.Others[device_name] = devices
 		ascend_ignored_list = append(ascend_ignored_list, devices.GetIgnoredDevices()...)
 	}
-	IgnoredDevicesList.Set(
+	klog.V(5).Infof("ascend_ignored_list is %v", ascend_ignored_list)
```
Comment (DSFans2014) [inline pkg/scheduler/api/node_info.go]: Please merge or rebase the latest code of master, there may be some conflicts.

Comment (kiritoxkiriko) [reply pkg/scheduler/api/node_info.go]: done

File: pkg/scheduler/api/node_info.go [hunk 4]
```diff
@@ -366,7 +366,11 @@ func (ni *NodeInfo) setNodeOthersResource(node *v1.Node) {
 			ignored_list = append(ignored_list, devices.GetIgnoredDevices()...)
 		}
 	}
-	IgnoredDevicesList.Set(ignored_list)
+	klog.V(5).Infof("ascend_ignored_list is %v", ignored_list)
```
Comment (DSFans2014) [inline pkg/scheduler/api/node_info.go]: `ignored_list` includes all devices, not just ascend.

Comment (archlitchi) [reply pkg/scheduler/api/node_info.go]: hi @kiritoxkiriko could you resolve this? we're ready to integrate

Comment (kiritoxkiriko) [reply pkg/scheduler/api/node_info.go]: solved

**Review by archlitchi — APPROVED** [review]
/lgtm
