### PR TITLE
Fixed memory leak caused by metrics remaining due to race conditions

### LINKED ISSUE #4821: Memory leak caused by leftover metrics data
### Description

Due to race problem, Clearing up job metrics and writing job metrics are executed concurrently. This could lead to metrics being cleared before they are written, resulting in leftover metrics, leading not only the memory leaks but also to increasingly slow response times for the `/metrics` interface.

### Steps to reproduce the issue

This can occur when a large number of jobs that finish quickly are created.

In our production environment, a large number of pods are continuously created, and some of these pods terminate immediately after being scheduled.

The `unschedule_task_count`, `job_share`, and `job_retry_counts` metric for a job are written after the pod has been scheduled. Therefore, it's possible that a job has already been cleaned up by the `processCleanupJob` method, but its metrics are written afterwards, causing these metrics to remain permanently in memory.

After running continuously in our environment for a month, the amount of residual data in the metrics can reach nearly 100MB.This resulted in Prometheus scraping the scheduler's metrics data very slowly.
```
# curl -o /dev/null -s -w "Total Time: %{time_total}s\n" http://127.0.0.1:8080/metrics
Total Time: 10.126988s
# curl -s http://127.0.0.1:8080/metrics | grep job_share |  wc -l
207512
# kubectl get pg -A | wc -l
2280
```

### Describe the results you received and expected

There shouldn't be any leftover for these three job-related metrics `unschedule_task_count`, `job_share`, and `job_retry_counts` after the job has been deleted.

### What version of Volcano are you using?

v1.11.2

### Any other relevant information

_No response_

### PR DESCRIPTION
**Pull request by halcyon-r**
Verify that the job still exists before set job's metrics.

#### What type of PR is this?
/kind bug
#### What this PR does / why we need it:

Before writing the `unschedule_task_count`, `job_share`, and `job_retry_counts` metrics, check if the job exists to prevent leftover metrics.

#### Which issue(s) this PR fixes:

Fixes #4821 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/cache/interface.go [hunk 1]
```diff
@@ -92,6 +92,9 @@ type Cache interface {
 
 	// SharedDRAManager returns the shared DRAManager
 	SharedDRAManager() framework.SharedDRAManager
+
+	// IsJobTerminated returns if the job was terminated
+	IsJobTerminated(jobId string) bool
```
Comment (hajnalmt) [inline pkg/scheduler/cache/interface.go]: Why haven't you used `(jobId api.jobId)` here too?
You would have spared the casting in `cache.go`

**Review by hajnalmt — COMMENTED** [review]
Looks good to me, I had one question only.

Checked the occurancies too and the commit is fine (we don't update these metrics elsewehere which is surprising).

File: pkg/scheduler/cache/cache.go [hunk 2]
```diff
@@ -1100,6 +1100,16 @@ func (sc *SchedulerCache) processCleanupJob() {
 	}
 }
 
+func (sc *SchedulerCache) IsJobTerminated(jobId string) bool {
+	sc.Mutex.Lock()
```
Comment (hajnalmt) [inline pkg/scheduler/cache/cache.go:1104]: I have created an enhacement request for this as this should be a Read Lock on the long run.
See: https://github.com/volcano-sh/volcano/issues/4824

File: pkg/scheduler/cache/interface.go (hunk 1 above)
Comment (halcyon-r) [reply pkg/scheduler/cache/interface.go]: Yes, you are right. I‘ll optimize this part.

**Comment by JesseStutler** [comment]
@halcyon-r So it's the same issue here but with different solutions? https://github.com/volcano-sh/volcano/pull/4760 I prefer to check if the job still exist rather than use ttl way, but also let @fengruotj takes a look

File: pkg/scheduler/cache/interface.go [hunk 3]
```diff
@@ -92,6 +92,9 @@ type Cache interface {
 
 	// SharedDRAManager returns the shared DRAManager
 	SharedDRAManager() framework.SharedDRAManager
+
+	// IsJobTerminated returns if the job was terminated
+	IsJobTerminated(jobId api.JobID) bool
```
Comment (JesseStutler) [inline pkg/scheduler/cache/interface.go:97]: I feel that we are too arbitrary to add a method to the cache interface here, the cache is not like the design that an interface should have
