### PR TITLE
fix: task-topology plugin cannot handle the tasks whose name contains `-`

### LINKED ISSUE #2939: The task-topology plugin cannot handle the tasks whose name contains `-`
**What happened**:

Assume that we have a kubernetes cluster with two nodes and a simple job with topology annotations:

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  annotations:
    volcano.sh/task-topology-affinity: "nginx-worker,ubuntu-worker"
    volcano.sh/task-topology-anti-affinity: "nginx-worker"
  name: example-job-1
spec:
  minAvailable: 5
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 2
      name: nginx-worker
      template:
        spec:
          containers:
            - image: nginx
              name: nginx-main
          restartPolicy: OnFailure
    - replicas: 3
      name: ubuntu-worker
      template:
        spec:
          containers:
            - command:
                - sleep
                - inf
              image: ubuntu
              name: ubuntu-main
          restartPolicy: OnFailure
```

The names of the tasks in the job all contain char `-`. 

And the scheduler config file:

```yaml
actions: "enqueue, backfill"
tiers:
  - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: task-topology
```

After applying the job yaml, the task-topology plugin not works and we get the error log like:

```
I0627 12:21:06.479367   43679 topology.go:342] start to init task topology plugin, weight[1], defined order map[0:4 1:1 2:2 3:3]
I0627 12:21:06.479469   43679 topology.go:286] Job <default/example-job-1-506fbf7a-e9c1-4ae4-b37a-60b1d67f5ee3> affinity key invalid: task nginx-worker do not exist in job <default/example-job-1-506fbf7a-e9c1-4ae4-b37a-60b1d67f5ee3>.
I0627 12:21:06.479489   43679 topology.go:311] Job <default/example-job-1-506fbf7a-e9c1-4ae4-b37a-60b1d67f5ee3> affinity key invalid: task nginx-worker do not exist in job <default/example-job-1-506fbf7a-e9c1-4ae4-b37a-60b1d67f5ee3>.
I0627 12:21:06.479501   43679 topology.go:227] Failed to read task topology from job <default/example-job-1-506fbf7a-e9c1-4ae4-b37a-60b1d67f5ee3> annotations, error: task nginx-worker do not exist in job <default/example-job-1-506fbf7a-e9c1-4ae4-b37a-60b1d67f5ee3>.
```

And the pods are not scheduled as expect:

image

**What you expected to happen**:

The task-topology should work well and the nginx-worker pods should be scheduled into different nodes.

**How to reproduce it (as minimally and precisely as possible)**:

As described above.

**Anything else we need to know?**:

I check the code, and find the code may cause this bug https://github.com/volcano-sh/volcano/blob/ed5c215d415d98845949d0fde6707cab29621989/pkg/scheduler/plugins/task-topology/topology.go#L243-L274

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/amd64"}
  Kustomize Version: v5.0.1
  Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: minikube using hyperkit driver on macOS(Intel)
- Kernel (e.g. `uname -a`): `Linux volcano-demo 5.10.57 #1 SMP Mon Apr 3 23:35:10 UTC 2023 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by loheagn**
fix #2939

### CODE REVIEW

**Comment by hwdef** [comment]
@wangyang0616 
Please help me trigger the CI of this PR

**Comment by lowang-bh** [comment]
how about add some comments of the task name format in following codes. The task's name is from pod name which generate by job controlller.
```go
		i := len(task.Name) - 1
		for ; task.Name[i] != '-'; i-- {
		}
		tmpTaskName := strings.TrimPrefix(task.Name[:i], jobNamePrefix)
```

FYI: 
https://github.com/volcano-sh/volcano/blob/ed5c215d415d98845949d0fde6707cab29621989/pkg/controllers/job/job_controller_util.go#L39

File: pkg/scheduler/plugins/task-topology/topology.go [hunk 1]
```diff
@@ -247,10 +247,14 @@ func affinityCheck(job *api.JobInfo, affinity [][]string) error {
...
 	var taskRef = make(map[string]bool, taskNumber)
+	var jobNamePrefix = job.Name + "-"
 	for _, task := range job.Tasks {
-		tmpStrings := strings.Split(task.Name, "-")
-		if _, exist := taskRef[tmpStrings[len(tmpStrings)-2]]; !exist {
-			taskRef[tmpStrings[len(tmpStrings)-2]] = true
+		i := len(task.Name) - 1
+		for ; task.Name[i] != '-'; i-- {
+		}
+		tmpTaskName := strings.TrimPrefix(task.Name[:i], jobNamePrefix)
```
[the remark this answers is not in the document]
Comment (loheagn) [reply pkg/scheduler/plugins/task-topology/topology.go:255]: It looks sensible. I'll update it.

**Comment by loheagn** [comment]
@lowang-bh Hi, could help to reopen this pr? I forget to update this pr for a long time......

**Comment by Monokaix** [comment]
@loheagn Hi, are you still work on this?

**Comment by loheagn** [comment]
> @loheagn Hi, are you still work on this?

@Monokaix  Yes, but I dismiss the `reopen` event..... 

I'll update the code recently.

**Comment by loheagn** [comment]
@Monokaix Hi, I fixed the CI and this pr is ready for review

File: pkg/scheduler/plugins/task-topology/topology.go [hunk 2]
```diff
@@ -247,10 +247,16 @@ func affinityCheck(job *api.JobInfo, affinity [][]string) error {
 
 	var taskNumber = len(job.Tasks)
 	var taskRef = make(map[string]bool, taskNumber)
+	var jobNamePrefix = job.Name + "-"
 	for _, task := range job.Tasks {
-		tmpStrings := strings.Split(task.Name, "-")
-		if _, exist := taskRef[tmpStrings[len(tmpStrings)-2]]; !exist {
-			taskRef[tmpStrings[len(tmpStrings)-2]] = true
+		i := len(task.Name) - 1
+		for ; task.Name[i] != '-'; i-- {
```
Comment (Monokaix) [inline pkg/scheduler/plugins/task-topology/topology.go:253]: How about use `strings.LastIndex` directly to find the last `-` index?

Comment (loheagn) [reply pkg/scheduler/plugins/task-topology/topology.go]: Thanks. I fixed it.

File: pkg/scheduler/plugins/task-topology/topology.go [hunk 3]
```diff
@@ -247,10 +247,15 @@ func affinityCheck(job *api.JobInfo, affinity [][]string) error {
...
 	var taskRef = make(map[string]bool, taskNumber)
+	var jobNamePrefix = job.Name + "-"
 	for _, task := range job.Tasks {
-		tmpStrings := strings.Split(task.Name, "-")
-		if _, exist := taskRef[tmpStrings[len(tmpStrings)-2]]; !exist {
-			taskRef[tmpStrings[len(tmpStrings)-2]] = true
+		// the full task name looks like "${job name}-${task name}-${index}",
+		// so we can trim the jobNamePrefix and the indexSuffix to get the short task name.
+		tmpTaskName := task.Name[:strings.LastIndex(task.Name, "-")]
+		tmpTaskName = strings.TrimPrefix(tmpTaskName, jobNamePrefix)
```
Comment (Monokaix) [inline pkg/scheduler/plugins/task-topology/topology.go:255]: Rename tmpTaskName to taskName is better.

Comment (loheagn) [reply pkg/scheduler/plugins/task-topology/topology.go:255]: I'm concerned that this might lead to ambiguity, as tmpTaskName is not the actual name of the task.

Comment (Monokaix) [reply pkg/scheduler/plugins/task-topology/topology.go:255]: I did not notice that, you're right: )

**Comment by loheagn** [comment]
hello, @Monokaix could we move this PR forward?

**Review by william-wang — APPROVED** [review]
/approve
